"use client"

import { createContext, useContext, useEffect, useMemo, useState } from "react"

export type Language =
  | "en"
  | "de"
  | "es"
  | "it"
  | "ar"
  | "zh"
  | "ja"
  | "th"
  | "fi"
  | "nl"
  | "de-CH"
  | "fr"
  | "sv"
  | "pt"

export type LanguageOption = {
  code: Language
  shortLabel: string
  label: string
  localeName: string
  dir: "ltr" | "rtl"
}

export const languageOptions: LanguageOption[] = [
  { code: "en", shortLabel: "EN", label: "English", localeName: "English", dir: "ltr" },
  { code: "de", shortLabel: "DE", label: "Deutsch", localeName: "Deutsch", dir: "ltr" },
  { code: "es", shortLabel: "ES", label: "Spanisch", localeName: "Espanol", dir: "ltr" },
  { code: "it", shortLabel: "IT", label: "Italienisch", localeName: "Italiano", dir: "ltr" },
  { code: "ar", shortLabel: "AR", label: "Arabisch", localeName: "Arabic", dir: "rtl" },
  { code: "zh", shortLabel: "ZH", label: "Chinesisch", localeName: "Chinese", dir: "ltr" },
  { code: "ja", shortLabel: "JA", label: "Japanisch", localeName: "Japanese", dir: "ltr" },
  { code: "th", shortLabel: "TH", label: "Thailaendisch", localeName: "Thai", dir: "ltr" },
  { code: "fi", shortLabel: "FI", label: "Finnisch", localeName: "Suomi", dir: "ltr" },
  { code: "nl", shortLabel: "NL", label: "Niederlaendisch", localeName: "Nederlands", dir: "ltr" },
  { code: "de-CH", shortLabel: "CH", label: "Schweizer Deutsch", localeName: "Schweizer Deutsch", dir: "ltr" },
  { code: "fr", shortLabel: "FR", label: "Franzoesisch", localeName: "Francais", dir: "ltr" },
  { code: "sv", shortLabel: "SV", label: "Schwedisch", localeName: "Svenska", dir: "ltr" },
  { code: "pt", shortLabel: "PT", label: "Portugiesisch", localeName: "Portugues", dir: "ltr" },
]

type LanguageContextValue = {
  language: Language
  setLanguage: (language: Language) => void
  currentLanguage: LanguageOption
  isRTL: boolean
  t: (key: string) => string
}

const defaultTranslations: Record<string, string> = {
  "nav.home": "Home",
  "nav.platforms": "Plattformen",
  "nav.products": "Produkte",
  "nav.solutions": "Loesungen",
  "nav.news": "KI Feed",
  "nav.pricing": "Preise",
  "nav.contact": "Kontakt",
  "nav.voiceAgent": "Try our AI Voice Agent",
  "nav.getStarted": "Loslegen",
  "nav.language": "Sprache",
  "hero.word.legaltech": "LegalTech",
  "hero.word.voicebots": "Voicebots",
  "hero.word.robotics": "Robotik",
  "hero.word.realEstate": "Immobilien",
  "hero.word.aviation": "Aviation",
  "hero.titleSuffix": "unter einer starken AI-Marke.",
  "hero.subtitle":
    "LetAIwork4u verbindet hochwertige Software, KI-Automation und neue Plattformideen. AnwaltSoft und beA4Outlook werden als Premium-Flagship fuer Kanzleien aufgebaut.",
  "hero.cta.platforms": "Plattformen ansehen",
  "hero.cta.anwaltsoft": "AnwaltSoft entdecken",
  "spline.title": "LETAIWORK4U Interaktive Erfahrung",
  "spline.subtitle": "Erkunden Sie unsere KI-Plattform mit immersiven 3D-Visualisierungen",
  "spline.cardTitle": "KI-gestuetzte Loesungen",
  "spline.cardText":
    "LETAIWORK4U bringt Ihr Unternehmen mit intelligenten KI-Loesungen voran. Schaffen Sie immersive Erlebnisse, die Workflows transformieren und Produktivitaet steigern.",
  "home.ecosystem.eyebrow": "LetAIwork4u Oekosystem",
  "home.ecosystem.title": "Eine Dachmarke fuer KI, LegalTech, Voicebots, Robotik und neue Plattformideen.",
  "home.ecosystem.desc":
    "AnwaltSoft und beA4Outlook werden als Flagship-Produkte aufgebaut. Weitere Plattformen koennen sauber wachsen, ohne die Marke jedes Mal neu zu erfinden.",
  "home.ecosystem.cta": "Alle Plattformen ansehen",
  "platform.anwaltsoft.eyebrow": "LegalTech Plattform",
  "platform.anwaltsoft.name": "AnwaltSoft",
  "platform.anwaltsoft.summary":
    "DMS, Kanzlei-Workflows, Dokumente, beA-nahe Prozesse und KI-Unterstuetzung fuer moderne Kanzleien.",
  "platform.bea4outlook.eyebrow": "Flagship Produkt",
  "platform.bea4outlook.name": "beA4Outlook",
  "platform.bea4outlook.summary":
    "beA-Nachrichten und Outlook E-Mails in einer vertrauten Arbeitsumgebung, inklusive Hashdateien und Zertifikatslogin.",
  "home.discover.title": "Entdecken Sie unsere KI-gestuetzten Loesungen",
  "home.discover.desc":
    "LETAIWORK4U bietet alles, was Sie brauchen, um Ihr Unternehmen mit moderner KI-Technologie weiterzuentwickeln.",
  "animated.prefix": "Ihr",
  "animated.suffix": "verdient bessere Werkzeuge",
  "animated.word.business": "Unternehmen",
  "animated.word.team": "Team",
  "animated.word.workflow": "Workflow",
  "animated.word.productivity": "Produktivitaet",
  "animated.word.strategy": "KI-Strategie",
  "animated.word.transformation": "digitale Transformation",
  "animated.word.automation": "Automatisierung",
  "animated.word.analytics": "Analytics",
  "features.title": "KI-Loesungen, die uns unterscheiden",
  "features.subtitle": "Entdecken Sie, warum LETAIWORK4U ein bevorzugter KI-Partner fuer moderne Unternehmen ist",
  "features.developers.title": "Gebaut fuer Entwickler",
  "features.developers.desc": "Fuer Engineers, Entwickler und Innovatoren, die KI in ihren Projekten nutzen wollen.",
  "features.ease.title": "Einfach nutzbar",
  "features.ease.desc": "Unsere KI-Loesungen sind intuitiv, zugaenglich und brauchen wenig technisches Vorwissen.",
  "features.pricing.title": "Transparente Preise",
  "features.pricing.desc": "Klare, planbare Preise ohne versteckte Gebuehren. Sie zahlen nur, was Sie nutzen.",
  "features.uptime.title": "99.9% Uptime Garantie",
  "features.uptime.desc": "Unsere robuste Infrastruktur sorgt dafuer, dass Ihre KI-Services verfuegbar bleiben.",
  "features.multi.title": "Multi-Tenant Architektur",
  "features.multi.desc": "KI-Ressourcen sicher im Unternehmen teilen, mit rollenbasiertem Zugriff.",
  "features.support.title": "24/7 AI Support",
  "features.support.desc": "Hilfe jederzeit durch KI-gestuetzten Support und menschliche Experten.",
  "features.improvement.title": "Kontinuierliche Verbesserung",
  "features.improvement.desc": "Unsere KI-Modelle lernen und verbessern sich, damit Ergebnisse mit der Zeit besser werden.",
  "features.custom.title": "Individuelle Loesungen",
  "features.custom.desc": "Wir passen KI-Loesungen an Ihre Branche, Prozesse und Ziele an.",
  "capabilities.title": "KI-gestuetzte Funktionen",
  "capabilities.subtitle": "Entdecken Sie unsere innovativen KI-Funktionen mit interaktiven Leuchtkarten",
  "capabilities.automation.title": "KI-gestuetzte Automatisierung",
  "capabilities.automation.desc": "Optimieren Sie Workflows mit intelligenter Automatisierung, die lernt und sich anpasst.",
  "capabilities.analytics.title": "Advanced Analytics",
  "capabilities.analytics.desc": "Gewinnen Sie verwertbare Erkenntnisse aus Daten mit leistungsstarken KI-Analytics.",
  "capabilities.security.title": "Sichere KI-Integration",
  "capabilities.security.desc": "Enterprise-Sicherheit fuer KI-Implementierung und Datenverarbeitung.",
  "capabilities.custom.title": "Custom AI Solutions",
  "capabilities.custom.desc": "Massgeschneiderte KI-Loesungen fuer Ihre Branche und Ihre Herausforderungen.",
  "capabilities.search.title": "Intelligente Suche",
  "capabilities.search.desc": "Finden Sie schneller, was Sie brauchen, mit KI-Suche, die Kontext und Absicht versteht.",
  "testimonials.title": "Was unsere Kunden sagen",
  "testimonials.subtitle": "Lesen Sie, wie zufriedene Kunden mit LETAIWORK4U arbeiten",
  "testimonials.0.role": "CTO bei TechCorp",
  "testimonials.0.content":
    "LETAIWORK4U hat veraendert, wie unser Team mit KI arbeitet. Die Loesungen sind intuitiv und der Support ist stark.",
  "testimonials.1.role": "Produktmanagerin",
  "testimonials.1.content":
    "Ich habe viele KI-Plattformen getestet, aber LETAIWORK4U ueberzeugt durch einfache Nutzung und starke Funktionen.",
  "testimonials.2.role": "Startup-Gruender",
  "testimonials.2.content":
    "Als Gruender brauchte ich verlaessliche KI-Loesungen, die skalieren koennen. LETAIWORK4U hat meine Erwartungen uebertroffen.",
  "testimonials.3.role": "Marketing Director",
  "testimonials.3.content":
    "Die KI-Analytics geben uns Einblicke, die wir vorher nicht hatten. Das hat unsere Marketingstrategie deutlich verbessert.",
  "footer.desc": "Muttermarke fuer KI-Integration, Voicebots, LegalTech, Software, Webdesign und neue AI-Projekte.",
  "footer.ecosystem": "Oekosystem",
  "contact.title": "Kontakt",
  "contact.subtitle": "Sprechen wir ueber KI, Automatisierung, Voicebots oder LegalTech.",
  "contact.callUs": "Anrufen",
  "contact.callUsDesc": "Direkter Kontakt fuer Beratung und Projektstart.",
  "contact.emailUs": "E-Mail",
  "contact.emailUsDesc": "Schreiben Sie uns Ihre Idee oder Anfrage.",
  "contact.consultation": "Beratung",
  "contact.consultationDesc": "Kostenloser Ersttermin fuer passende naechste Schritte.",
  "contact.formBelow": "Formular unten nutzen",
  "contact.sendMessage": "Nachricht senden",
  "contact.messageSent": "Nachricht gesendet",
  "contact.thankYou": "Danke. Wir melden uns zeitnah.",
  "contact.fullName": "Name",
  "contact.email": "E-Mail",
  "contact.company": "Firma",
  "contact.phone": "Telefon",
  "contact.productInterest": "Interesse",
  "contact.message": "Nachricht",
  "contact.submit": "Anfrage absenden",
  "contact.whyChoose": "Warum LetAIwork4u",
  "contact.cuttingEdge": "Moderne KI",
  "contact.cuttingEdgeDesc": "Praxisnahe Automatisierung statt Buzzwords.",
  "contact.expertTeam": "Umsetzung aus einer Hand",
  "contact.expertTeamDesc": "Strategie, Design, Software und Integration.",
  "contact.provenResults": "Fokus auf Ergebnis",
  "contact.provenResultsDesc": "Workflows, die Zeit sparen und messbar helfen.",
  "products.title": "Produkte",
  "products.subtitle": "KI-Produkte, Automatisierung und LegalTech aus dem LetAIwork4u Oekosystem.",
  "products.enterpriseAIChatbot.title": "Enterprise AI Chatbot",
  "products.enterpriseAIChatbot.description": "KI-Chatbot fuer Support, Vertrieb und interne Wissensprozesse.",
  "products.intelligentVoiceAssistant.title": "Intelligent Voice Assistant",
  "products.intelligentVoiceAssistant.description": "Telefon- und Voicebot-Automatisierung mit Weiterleitung und Terminlogik.",
  "products.businessProcessAutomation.title": "Business Process Automation",
  "products.businessProcessAutomation.description": "Automatisierte Workflows fuer wiederkehrende Aufgaben und Dokumente.",
  "products.predictiveAnalyticsPlatform.title": "Predictive Analytics Platform",
  "products.predictiveAnalyticsPlatform.description": "Aus Daten bessere Entscheidungen, Prognosen und Dashboards machen.",
  "products.customAIDevelopment.title": "Custom AI Development",
  "products.customAIDevelopment.description": "Massgeschneiderte KI-Loesungen fuer spezielle Prozesse.",
  "products.aiImplementationServices.title": "AI Implementation Services",
  "products.aiImplementationServices.description": "Beratung, Einfuehrung, Schulung und laufende Optimierung.",
  "products.category.chatbots": "Chatbots",
  "products.category.voiceAssistants": "Voice Assistants",
  "products.category.automation": "Automation",
  "products.category.analytics": "Analytics",
  "products.category.customSolutions": "Custom AI",
  "products.category.consulting": "Consulting",
  "products.keyFeatures": "Kernfunktionen",
  "products.viewDetails": "Details ansehen",
}

const translations: Partial<Record<Language, Record<string, string>>> = {
  de: defaultTranslations,
  "de-CH": {
    ...defaultTranslations,
    "nav.platforms": "Plattformen",
    "nav.solutions": "Loesige",
    "nav.pricing": "Priise",
    "nav.contact": "Kontakt",
  },
  en: {
    ...defaultTranslations,
    "nav.platforms": "Platforms",
    "nav.products": "Products",
    "nav.solutions": "Solutions",
    "nav.news": "AI Feed",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    "nav.getStarted": "Get Started",
    "nav.language": "Language",
    "contact.title": "Contact",
    "products.title": "Products",
    "hero.titleSuffix": "under one strong AI brand.",
    "hero.subtitle":
      "LetAIwork4u connects premium software, AI automation, and new platform ideas. AnwaltSoft and beA4Outlook are being built as flagship products for law firms.",
    "hero.cta.platforms": "View platforms",
    "hero.cta.anwaltsoft": "Discover AnwaltSoft",
    "spline.title": "LETAIWORK4U Interactive Experience",
    "spline.subtitle": "Explore our AI-powered platform with immersive 3D visualizations",
    "spline.cardTitle": "AI-Powered Solutions",
    "spline.cardText":
      "LETAIWORK4U brings your business to life with intelligent AI solutions. Create immersive experiences that transform your workflow and enhance productivity.",
    "home.ecosystem.eyebrow": "LetAIwork4u ecosystem",
    "home.ecosystem.title": "One umbrella brand for AI, LegalTech, voicebots, robotics, and new platform ideas.",
    "home.ecosystem.desc":
      "AnwaltSoft and beA4Outlook are being built as flagship products. Additional platforms can grow cleanly without reinventing the brand every time.",
    "home.ecosystem.cta": "View all platforms",
    "home.discover.title": "Discover our AI-powered solutions",
    "home.discover.desc":
      "LETAIWORK4U provides everything you need to transform your business with cutting-edge AI technology.",
    "animated.prefix": "Your",
    "animated.suffix": "deserves better tools",
    "animated.word.business": "business",
    "animated.word.team": "team",
    "animated.word.workflow": "workflow",
    "animated.word.productivity": "productivity",
    "animated.word.strategy": "AI strategy",
    "animated.word.transformation": "digital transformation",
    "animated.word.automation": "automation",
    "animated.word.analytics": "analytics",
    "features.title": "AI Solutions that set us apart",
    "features.subtitle": "Discover why LETAIWORK4U is the preferred AI partner for businesses worldwide",
    "features.developers.title": "Built for developers",
    "features.developers.desc": "Designed for engineers, developers, and innovators who want to leverage AI in their projects.",
    "features.ease.title": "Ease of use",
    "features.ease.desc": "Our AI solutions are intuitive and accessible, requiring minimal technical expertise.",
    "features.pricing.title": "Transparent pricing",
    "features.pricing.desc": "Clear, predictable pricing with no hidden fees. Pay only for what you use.",
    "features.uptime.title": "99.9% Uptime guarantee",
    "features.uptime.desc": "Our robust infrastructure ensures your AI services are always available when you need them.",
    "features.multi.title": "Multi-tenant Architecture",
    "features.multi.desc": "Securely share AI resources across your organization with role-based access control.",
    "features.support.title": "24/7 AI Support",
    "features.support.desc": "Get help anytime with our AI-powered support system and dedicated human experts.",
    "features.improvement.title": "Continuous improvement",
    "features.improvement.desc": "Our AI models are constantly learning and improving to deliver better results over time.",
    "features.custom.title": "Custom solutions",
    "features.custom.desc": "We tailor our AI solutions to meet your specific business needs and challenges.",
    "capabilities.title": "AI-Powered Capabilities",
    "capabilities.subtitle": "Discover our innovative AI features with interactive glowing cards",
    "capabilities.automation.title": "AI-Powered Automation",
    "capabilities.automation.desc": "Streamline your workflows with intelligent automation that learns and adapts to your business needs.",
    "capabilities.analytics.title": "Advanced Analytics",
    "capabilities.analytics.desc": "Gain actionable insights from your data with our powerful AI analytics tools.",
    "capabilities.security.title": "Secure AI Integration",
    "capabilities.security.desc": "Enterprise-grade security for all your AI implementations and data processing.",
    "capabilities.custom.title": "Custom AI Solutions",
    "capabilities.custom.desc": "Tailored AI solutions designed specifically for your industry and business challenges.",
    "capabilities.search.title": "Intelligent Search",
    "capabilities.search.desc": "Find exactly what you need with our AI-powered search technology that understands context and intent.",
    "testimonials.title": "What Our Customers Say",
    "testimonials.subtitle": "Don't just take our word for it - hear from some of our satisfied customers",
    "footer.desc": "Umbrella brand for AI integration, voicebots, LegalTech, software, web design, and new AI projects.",
  },
  es: {
    ...defaultTranslations,
    "nav.products": "Productos",
    "nav.solutions": "Soluciones",
    "nav.pricing": "Precios",
    "nav.contact": "Contacto",
    "nav.language": "Idioma",
    "hero.titleSuffix": "bajo una marca de IA fuerte.",
    "hero.cta.platforms": "Ver plataformas",
    "hero.cta.anwaltsoft": "Descubrir AnwaltSoft",
    "spline.title": "Experiencia interactiva LETAIWORK4U",
    "spline.subtitle": "Explora nuestra plataforma de IA con visualizaciones 3D inmersivas",
    "spline.cardTitle": "Soluciones impulsadas por IA",
    "home.ecosystem.eyebrow": "Ecosistema LetAIwork4u",
    "home.ecosystem.title": "Una marca paraguas para IA, LegalTech, voicebots, robotica y nuevas plataformas.",
    "home.ecosystem.cta": "Ver todas las plataformas",
    "home.discover.title": "Descubre nuestras soluciones impulsadas por IA",
    "animated.prefix": "Tu",
    "animated.suffix": "merece mejores herramientas",
    "features.title": "Soluciones de IA que nos distinguen",
    "capabilities.title": "Capacidades impulsadas por IA",
    "testimonials.title": "Lo que dicen nuestros clientes",
    "footer.ecosystem": "Ecosistema",
  },
  it: {
    ...defaultTranslations,
    "nav.products": "Prodotti",
    "nav.solutions": "Soluzioni",
    "nav.pricing": "Prezzi",
    "nav.contact": "Contatto",
    "nav.language": "Lingua",
    "hero.titleSuffix": "sotto un forte marchio AI.",
    "hero.cta.platforms": "Vedi piattaforme",
    "hero.cta.anwaltsoft": "Scopri AnwaltSoft",
    "spline.title": "Esperienza interattiva LETAIWORK4U",
    "spline.subtitle": "Esplora la nostra piattaforma AI con visualizzazioni 3D immersive",
    "spline.cardTitle": "Soluzioni basate sull'AI",
    "home.ecosystem.eyebrow": "Ecosistema LetAIwork4u",
    "home.ecosystem.title": "Un marchio ombrello per AI, LegalTech, voicebot, robotica e nuove piattaforme.",
    "home.ecosystem.cta": "Vedi tutte le piattaforme",
    "home.discover.title": "Scopri le nostre soluzioni basate sull'AI",
    "animated.prefix": "La tua",
    "animated.suffix": "merita strumenti migliori",
    "features.title": "Soluzioni AI che ci distinguono",
    "capabilities.title": "Capacita basate sull'AI",
    "testimonials.title": "Cosa dicono i nostri clienti",
    "footer.ecosystem": "Ecosistema",
  },
  ar: {
    ...defaultTranslations,
    "nav.platforms": "المنصات",
    "nav.products": "المنتجات",
    "nav.solutions": "الحلول",
    "nav.news": "أخبار الذكاء الاصطناعي",
    "nav.pricing": "الأسعار",
    "nav.contact": "اتصال",
    "nav.language": "اللغة",
    "hero.titleSuffix": "تحت علامة قوية للذكاء الاصطناعي.",
    "hero.cta.platforms": "عرض المنصات",
    "hero.cta.anwaltsoft": "اكتشف AnwaltSoft",
    "spline.title": "تجربة LETAIWORK4U التفاعلية",
    "spline.subtitle": "استكشف منصتنا المدعومة بالذكاء الاصطناعي مع عروض ثلاثية الأبعاد",
    "spline.cardTitle": "حلول مدعومة بالذكاء الاصطناعي",
    "home.ecosystem.eyebrow": "منظومة LetAIwork4u",
    "home.ecosystem.title": "علامة واحدة للذكاء الاصطناعي وLegalTech وvoicebots والروبوتات والمنصات الجديدة.",
    "home.ecosystem.cta": "عرض كل المنصات",
    "home.discover.title": "اكتشف حلولنا المدعومة بالذكاء الاصطناعي",
    "animated.prefix": "عملك",
    "animated.suffix": "يستحق أدوات أفضل",
    "features.title": "حلول ذكاء اصطناعي تميزنا",
    "capabilities.title": "قدرات مدعومة بالذكاء الاصطناعي",
    "testimonials.title": "ماذا يقول عملاؤنا",
    "footer.ecosystem": "المنظومة",
  },
  zh: {
    ...defaultTranslations,
    "nav.platforms": "平台",
    "nav.products": "产品",
    "nav.solutions": "解决方案",
    "nav.news": "AI 动态",
    "nav.pricing": "价格",
    "nav.contact": "联系",
    "nav.language": "语言",
    "hero.titleSuffix": "汇聚在一个强大的 AI 品牌下。",
    "hero.cta.platforms": "查看平台",
    "hero.cta.anwaltsoft": "了解 AnwaltSoft",
    "spline.title": "LETAIWORK4U 互动体验",
    "spline.subtitle": "通过沉浸式 3D 可视化探索我们的 AI 平台",
    "spline.cardTitle": "AI 驱动的解决方案",
    "home.ecosystem.eyebrow": "LetAIwork4u 生态系统",
    "home.ecosystem.title": "一个覆盖 AI、LegalTech、语音机器人、机器人技术和新平台的品牌。",
    "home.ecosystem.cta": "查看所有平台",
    "home.discover.title": "探索我们的 AI 解决方案",
    "animated.prefix": "您的",
    "animated.suffix": "值得更好的工具",
    "features.title": "让我们与众不同的 AI 解决方案",
    "capabilities.title": "AI 驱动能力",
    "testimonials.title": "客户评价",
    "footer.ecosystem": "生态系统",
  },
  ja: {
    ...defaultTranslations,
    "nav.platforms": "プラットフォーム",
    "nav.products": "製品",
    "nav.solutions": "ソリューション",
    "nav.news": "AIフィード",
    "nav.pricing": "料金",
    "nav.contact": "お問い合わせ",
    "nav.language": "言語",
    "hero.titleSuffix": "強いAIブランドのもとに。",
    "hero.cta.platforms": "プラットフォームを見る",
    "hero.cta.anwaltsoft": "AnwaltSoftを見る",
    "spline.title": "LETAIWORK4U インタラクティブ体験",
    "spline.subtitle": "没入型3DビジュアルでAIプラットフォームを探索",
    "spline.cardTitle": "AI搭載ソリューション",
    "home.ecosystem.eyebrow": "LetAIwork4u エコシステム",
    "home.ecosystem.title": "AI、LegalTech、音声ボット、ロボティクス、新しいプラットフォームを束ねるブランド。",
    "home.ecosystem.cta": "すべてのプラットフォームを見る",
    "home.discover.title": "AIソリューションを見る",
    "animated.prefix": "あなたの",
    "animated.suffix": "にはより良いツールが必要です",
    "features.title": "私たちを際立たせるAIソリューション",
    "capabilities.title": "AI搭載機能",
    "testimonials.title": "お客様の声",
    "footer.ecosystem": "エコシステム",
  },
  th: {
    ...defaultTranslations,
    "nav.platforms": "แพลตฟอร์ม",
    "nav.products": "ผลิตภัณฑ์",
    "nav.solutions": "โซลูชัน",
    "nav.news": "ฟีด AI",
    "nav.pricing": "ราคา",
    "nav.contact": "ติดต่อ",
    "nav.language": "ภาษา",
    "hero.titleSuffix": "ภายใต้แบรนด์ AI ที่แข็งแกร่ง.",
    "hero.cta.platforms": "ดูแพลตฟอร์ม",
    "hero.cta.anwaltsoft": "รู้จัก AnwaltSoft",
    "spline.title": "ประสบการณ์โต้ตอบ LETAIWORK4U",
    "spline.subtitle": "สำรวจแพลตฟอร์ม AI ของเราด้วยภาพ 3D แบบ immersive",
    "spline.cardTitle": "โซลูชันขับเคลื่อนด้วย AI",
    "home.ecosystem.eyebrow": "ระบบนิเวศ LetAIwork4u",
    "home.ecosystem.title": "แบรนด์หลักสำหรับ AI, LegalTech, voicebots, หุ่นยนต์ และแพลตฟอร์มใหม่.",
    "home.ecosystem.cta": "ดูแพลตฟอร์มทั้งหมด",
    "home.discover.title": "ค้นพบโซลูชัน AI ของเรา",
    "animated.prefix": "",
    "animated.suffix": "ของคุณสมควรได้เครื่องมือที่ดีกว่า",
    "features.title": "โซลูชัน AI ที่ทำให้เราแตกต่าง",
    "capabilities.title": "ความสามารถที่ขับเคลื่อนด้วย AI",
    "testimonials.title": "ลูกค้าของเราพูดว่าอย่างไร",
    "footer.ecosystem": "ระบบนิเวศ",
  },
  fi: {
    ...defaultTranslations,
    "nav.products": "Tuotteet",
    "nav.solutions": "Ratkaisut",
    "nav.pricing": "Hinnat",
    "nav.contact": "Yhteys",
    "nav.language": "Kieli",
    "hero.titleSuffix": "vahvan AI-brändin alla.",
    "hero.cta.platforms": "Katso alustat",
    "hero.cta.anwaltsoft": "Tutustu AnwaltSoftiin",
    "spline.title": "LETAIWORK4U interaktiivinen kokemus",
    "spline.subtitle": "Tutustu AI-alustaamme immersiivisten 3D-visualisointien avulla",
    "spline.cardTitle": "AI-pohjaiset ratkaisut",
    "home.ecosystem.eyebrow": "LetAIwork4u-ekosysteemi",
    "home.ecosystem.title": "Yksi kattobrändi AI:lle, LegalTechille, voiceboteille, robotiikalle ja uusille alustoille.",
    "home.ecosystem.cta": "Katso kaikki alustat",
    "home.discover.title": "Tutustu AI-ratkaisuihimme",
    "animated.prefix": "Sinun",
    "animated.suffix": "ansaitsee paremmat työkalut",
    "features.title": "AI-ratkaisut, jotka erottavat meidät",
    "capabilities.title": "AI-pohjaiset kyvykkyydet",
    "testimonials.title": "Mitä asiakkaamme sanovat",
    "footer.ecosystem": "Ekosysteemi",
  },
  nl: {
    ...defaultTranslations,
    "nav.products": "Producten",
    "nav.solutions": "Oplossingen",
    "nav.pricing": "Prijzen",
    "nav.contact": "Contact",
    "nav.language": "Taal",
    "hero.titleSuffix": "onder een sterk AI-merk.",
    "hero.cta.platforms": "Bekijk platforms",
    "hero.cta.anwaltsoft": "Ontdek AnwaltSoft",
    "spline.title": "LETAIWORK4U interactieve ervaring",
    "spline.subtitle": "Ontdek ons AI-platform met immersieve 3D-visualisaties",
    "spline.cardTitle": "AI-gedreven oplossingen",
    "home.ecosystem.eyebrow": "LetAIwork4u ecosysteem",
    "home.ecosystem.title": "Een overkoepelend merk voor AI, LegalTech, voicebots, robotica en nieuwe platformideeen.",
    "home.ecosystem.cta": "Bekijk alle platforms",
    "home.discover.title": "Ontdek onze AI-oplossingen",
    "animated.prefix": "Uw",
    "animated.suffix": "verdient betere tools",
    "features.title": "AI-oplossingen die ons onderscheiden",
    "capabilities.title": "AI-gedreven mogelijkheden",
    "testimonials.title": "Wat onze klanten zeggen",
    "footer.ecosystem": "Ecosysteem",
  },
  fr: {
    ...defaultTranslations,
    "nav.products": "Produits",
    "nav.solutions": "Solutions",
    "nav.pricing": "Tarifs",
    "nav.contact": "Contact",
    "nav.language": "Langue",
    "hero.titleSuffix": "sous une marque IA forte.",
    "hero.cta.platforms": "Voir les plateformes",
    "hero.cta.anwaltsoft": "Decouvrir AnwaltSoft",
    "spline.title": "Experience interactive LETAIWORK4U",
    "spline.subtitle": "Explorez notre plateforme IA avec des visualisations 3D immersives",
    "spline.cardTitle": "Solutions propulsees par l'IA",
    "home.ecosystem.eyebrow": "Ecosysteme LetAIwork4u",
    "home.ecosystem.title": "Une marque ombrelle pour l'IA, LegalTech, les voicebots, la robotique et les nouvelles plateformes.",
    "home.ecosystem.cta": "Voir toutes les plateformes",
    "home.discover.title": "Decouvrez nos solutions IA",
    "animated.prefix": "Votre",
    "animated.suffix": "merite de meilleurs outils",
    "features.title": "Des solutions IA qui nous distinguent",
    "capabilities.title": "Capacites propulsees par l'IA",
    "testimonials.title": "Ce que disent nos clients",
    "footer.ecosystem": "Ecosysteme",
  },
  sv: {
    ...defaultTranslations,
    "nav.products": "Produkter",
    "nav.solutions": "Loesningar",
    "nav.pricing": "Priser",
    "nav.contact": "Kontakt",
    "nav.language": "Sprak",
    "hero.titleSuffix": "under ett starkt AI-varumarke.",
    "hero.cta.platforms": "Visa plattformar",
    "hero.cta.anwaltsoft": "Upptack AnwaltSoft",
    "spline.title": "LETAIWORK4U interaktiv upplevelse",
    "spline.subtitle": "Utforska var AI-plattform med immersiva 3D-visualiseringar",
    "spline.cardTitle": "AI-drivna loesningar",
    "home.ecosystem.eyebrow": "LetAIwork4u ekosystem",
    "home.ecosystem.title": "Ett paraplyvarumarke for AI, LegalTech, voicebots, robotik och nya plattformar.",
    "home.ecosystem.cta": "Visa alla plattformar",
    "home.discover.title": "Upptack vara AI-loesningar",
    "animated.prefix": "Din",
    "animated.suffix": "fortjanar battre verktyg",
    "features.title": "AI-loesningar som skiljer oss fran mangden",
    "capabilities.title": "AI-drivna funktioner",
    "testimonials.title": "Vad vara kunder sager",
    "footer.ecosystem": "Ekosystem",
  },
  pt: {
    ...defaultTranslations,
    "nav.products": "Produtos",
    "nav.solutions": "Solucoes",
    "nav.pricing": "Precos",
    "nav.contact": "Contato",
    "nav.language": "Idioma",
    "hero.titleSuffix": "sob uma marca forte de IA.",
    "hero.cta.platforms": "Ver plataformas",
    "hero.cta.anwaltsoft": "Conhecer AnwaltSoft",
    "spline.title": "Experiencia interativa LETAIWORK4U",
    "spline.subtitle": "Explore nossa plataforma de IA com visualizacoes 3D imersivas",
    "spline.cardTitle": "Solucoes impulsionadas por IA",
    "home.ecosystem.eyebrow": "Ecossistema LetAIwork4u",
    "home.ecosystem.title": "Uma marca guarda-chuva para IA, LegalTech, voicebots, robotica e novas plataformas.",
    "home.ecosystem.cta": "Ver todas as plataformas",
    "home.discover.title": "Conheca nossas solucoes de IA",
    "animated.prefix": "Seu",
    "animated.suffix": "merece ferramentas melhores",
    "features.title": "Solucoes de IA que nos diferenciam",
    "capabilities.title": "Capacidades impulsionadas por IA",
    "testimonials.title": "O que nossos clientes dizem",
    "footer.ecosystem": "Ecossistema",
  },
}

const supplementalTranslations: Partial<Record<Language, Record<string, string>>> = {
  en: {
    "platform.anwaltsoft.eyebrow": "LegalTech Platform",
    "platform.anwaltsoft.summary":
      "DMS, law-firm workflows, documents, beA-adjacent processes, and AI support for modern legal teams.",
    "platform.bea4outlook.eyebrow": "Flagship Product",
    "platform.bea4outlook.summary":
      "beA messages and Outlook email in one familiar workspace, including hash files and certificate-based login.",
    "testimonials.0.role": "CTO at TechCorp",
    "testimonials.0.content":
      "LETAIWORK4U has completely transformed how our team works with AI. The solutions are intuitive and the support is outstanding.",
    "testimonials.1.role": "Product Manager",
    "testimonials.1.content":
      "I have tried many AI platforms, but LETAIWORK4U stands out for ease of use and powerful capabilities.",
    "testimonials.2.role": "Startup Founder",
    "testimonials.2.content":
      "As a founder, I needed reliable AI solutions that could scale. LETAIWORK4U exceeded my expectations.",
    "testimonials.3.role": "Marketing Director",
    "testimonials.3.content":
      "The AI analytics features have given us insights we never had before. They changed how we plan marketing.",
  },
  es: {
    "hero.subtitle":
      "LetAIwork4u conecta software premium, automatizacion con IA y nuevas ideas de plataforma. AnwaltSoft y beA4Outlook se construyen como productos insignia para despachos.",
    "spline.cardText":
      "LETAIWORK4U impulsa tu empresa con soluciones inteligentes de IA que transforman procesos y aumentan la productividad.",
    "home.ecosystem.desc":
      "AnwaltSoft y beA4Outlook se desarrollan como productos insignia. Otras plataformas pueden crecer de forma clara sin reinventar la marca.",
    "home.discover.desc":
      "LETAIWORK4U ofrece lo necesario para transformar tu negocio con tecnologia de IA avanzada.",
    "features.subtitle": "Descubre por que LETAIWORK4U es un socio de IA preferido por empresas modernas.",
    "features.developers.title": "Creado para desarrolladores",
    "features.developers.desc": "Para equipos tecnicos e innovadores que quieren usar IA en proyectos reales.",
    "features.ease.title": "Facil de usar",
    "features.ease.desc": "Soluciones de IA intuitivas, accesibles y listas para el trabajo diario.",
    "features.pricing.title": "Precios transparentes",
    "features.pricing.desc": "Precios claros y previsibles, sin costes ocultos.",
    "features.uptime.title": "Alta disponibilidad",
    "features.uptime.desc": "Infraestructura robusta para que tus servicios de IA esten disponibles.",
    "features.multi.title": "Arquitectura multiusuario",
    "features.multi.desc": "Comparte recursos de IA con control de acceso por roles.",
    "features.support.title": "Soporte IA 24/7",
    "features.support.desc": "Ayuda continua con soporte impulsado por IA y expertos humanos.",
    "features.improvement.title": "Mejora continua",
    "features.improvement.desc": "Los modelos mejoran con el tiempo para entregar mejores resultados.",
    "features.custom.title": "Soluciones a medida",
    "features.custom.desc": "Adaptamos la IA a tus procesos, sector y objetivos.",
    "capabilities.subtitle": "Explora funciones innovadoras de IA en tarjetas interactivas.",
    "capabilities.automation.title": "Automatizacion con IA",
    "capabilities.automation.desc": "Optimiza flujos de trabajo con automatizacion inteligente.",
    "capabilities.analytics.title": "Analitica avanzada",
    "capabilities.analytics.desc": "Convierte tus datos en informacion accionable.",
    "capabilities.security.title": "Integracion segura de IA",
    "capabilities.security.desc": "Seguridad empresarial para implementaciones y datos.",
    "capabilities.custom.title": "Soluciones IA a medida",
    "capabilities.custom.desc": "IA disenada para tu industria y tus retos.",
    "capabilities.search.title": "Busqueda inteligente",
    "capabilities.search.desc": "Encuentra informacion con busqueda que entiende contexto e intencion.",
    "platform.anwaltsoft.eyebrow": "Plataforma LegalTech",
    "platform.anwaltsoft.summary": "DMS, flujos de despacho, documentos, procesos cercanos a beA y apoyo de IA.",
    "platform.bea4outlook.eyebrow": "Producto insignia",
    "platform.bea4outlook.summary": "Mensajes beA y correos Outlook en un entorno familiar, con hash y certificado.",
    "testimonials.subtitle": "Escucha lo que dicen clientes satisfechos.",
    "testimonials.0.role": "CTO en TechCorp",
    "testimonials.0.content": "LETAIWORK4U cambio nuestra forma de trabajar con IA. Es intuitivo y el soporte es excelente.",
    "testimonials.1.role": "Product Manager",
    "testimonials.1.content": "He probado muchas plataformas de IA; LETAIWORK4U destaca por facilidad y potencia.",
    "testimonials.2.role": "Fundador de startup",
    "testimonials.2.content": "Necesitaba IA fiable y escalable. LETAIWORK4U supero mis expectativas.",
    "testimonials.3.role": "Directora de marketing",
    "testimonials.3.content": "La analitica con IA nos dio informacion nueva para mejorar la estrategia.",
    "footer.desc": "Marca paraguas para integracion de IA, voicebots, LegalTech, software, webdesign y nuevos proyectos.",
  },
  it: {
    "hero.subtitle":
      "LetAIwork4u unisce software premium, automazione AI e nuove idee di piattaforma. AnwaltSoft e beA4Outlook sono prodotti flagship per studi legali.",
    "spline.cardText":
      "LETAIWORK4U porta l'AI nei processi aziendali con soluzioni intelligenti che migliorano workflow e produttivita.",
    "home.ecosystem.desc":
      "AnwaltSoft e beA4Outlook crescono come prodotti flagship. Altre piattaforme possono evolvere senza reinventare il brand.",
    "home.discover.desc": "LETAIWORK4U offre strumenti per trasformare il business con tecnologia AI avanzata.",
    "features.subtitle": "Scopri perche LETAIWORK4U e un partner AI preferito dalle aziende moderne.",
    "features.developers.title": "Creato per sviluppatori",
    "features.developers.desc": "Per team tecnici e innovatori che vogliono usare l'AI in progetti concreti.",
    "features.ease.title": "Facile da usare",
    "features.ease.desc": "Soluzioni AI intuitive e accessibili per il lavoro quotidiano.",
    "features.pricing.title": "Prezzi trasparenti",
    "features.pricing.desc": "Prezzi chiari e prevedibili, senza costi nascosti.",
    "features.uptime.title": "Alta disponibilita",
    "features.uptime.desc": "Infrastruttura robusta per mantenere disponibili i servizi AI.",
    "features.multi.title": "Architettura multi-tenant",
    "features.multi.desc": "Condivisione sicura delle risorse AI con accessi basati sui ruoli.",
    "features.support.title": "Supporto AI 24/7",
    "features.support.desc": "Aiuto continuo con supporto AI ed esperti umani.",
    "features.improvement.title": "Miglioramento continuo",
    "features.improvement.desc": "I modelli migliorano nel tempo per risultati sempre migliori.",
    "features.custom.title": "Soluzioni su misura",
    "features.custom.desc": "Adattiamo l'AI a processi, settore e obiettivi.",
    "capabilities.subtitle": "Scopri funzioni AI innovative con card interattive.",
    "capabilities.automation.title": "Automazione AI",
    "capabilities.automation.desc": "Ottimizza i workflow con automazione intelligente.",
    "capabilities.analytics.title": "Analisi avanzata",
    "capabilities.analytics.desc": "Trasforma i dati in insight utilizzabili.",
    "capabilities.security.title": "Integrazione AI sicura",
    "capabilities.security.desc": "Sicurezza enterprise per implementazioni e dati.",
    "capabilities.custom.title": "Soluzioni AI personalizzate",
    "capabilities.custom.desc": "AI progettata per il tuo settore e le tue sfide.",
    "capabilities.search.title": "Ricerca intelligente",
    "capabilities.search.desc": "Trova informazioni con una ricerca che capisce contesto e intenzione.",
    "platform.anwaltsoft.eyebrow": "Piattaforma LegalTech",
    "platform.anwaltsoft.summary": "DMS, workflow legali, documenti, processi vicini a beA e supporto AI.",
    "platform.bea4outlook.eyebrow": "Prodotto flagship",
    "platform.bea4outlook.summary": "Messaggi beA e email Outlook in un ambiente familiare, con hash e certificato.",
    "testimonials.subtitle": "Ascolta cosa dicono alcuni clienti soddisfatti.",
    "testimonials.0.role": "CTO presso TechCorp",
    "testimonials.0.content": "LETAIWORK4U ha cambiato il modo in cui lavoriamo con l'AI. Intuitivo e con ottimo supporto.",
    "testimonials.1.role": "Product Manager",
    "testimonials.1.content": "Ho provato molte piattaforme AI; LETAIWORK4U spicca per facilita e potenza.",
    "testimonials.2.role": "Fondatore startup",
    "testimonials.2.content": "Avevo bisogno di AI affidabile e scalabile. LETAIWORK4U ha superato le aspettative.",
    "testimonials.3.role": "Marketing Director",
    "testimonials.3.content": "Le analytics AI ci hanno dato insight nuovi per migliorare la strategia.",
    "footer.desc": "Brand ombrello per integrazione AI, voicebot, LegalTech, software, webdesign e nuovi progetti.",
  },
}

const expandedHomepageTranslations: Partial<Record<Language, Record<string, string>>> = {
  "de-CH": {
    "nav.getStarted": "Loslege",
    "hero.subtitle":
      "LetAIwork4u verbindet hochwertigi Software, KI-Automatisierig und neui Plattformidee. AnwaltSoft und beA4Outlook waerled als Flagship-Produkte fuer Kanzleie ufbaut.",
    "spline.title": "LETAIWORK4U Interaktivi Erfahrig",
    "spline.subtitle": "Entdecke Sie eusi KI-Plattform mit immersive 3D-Visualisierige",
    "spline.cardTitle": "KI-gstuetzti Loesige",
    "spline.cardText":
      "LETAIWORK4U bringt Ihr Unternehmen mit intelligente KI-Loesige voran und verbessert Workflows sowie Produktivitaet.",
    "home.ecosystem.desc":
      "AnwaltSoft und beA4Outlook waerled als Flagship-Produkte ufbaut. Witeri Plattformen chönd sauber wachse.",
    "home.discover.title": "Entdecke Sie eusi KI-gstuetzte Loesige",
    "home.discover.desc": "LETAIWORK4U bietet alles fuer d Transformation mit moderne KI-Technologie.",
    "features.subtitle": "Entdecke Sie, warum LETAIWORK4U e bevorzugte KI-Partner fuer moderne Unternehmen isch.",
    "capabilities.subtitle": "Entdecke Sie innovativi KI-Funktionen mit interaktive Charte.",
    "testimonials.subtitle": "Lese Sie, wie zfriedeni Chunde mit LETAIWORK4U schaffe.",
    "footer.desc": "Dachmarke fuer KI-Integration, Voicebots, LegalTech, Software, Webdesign und neui AI-Projekte.",
  },
  es: { "nav.getStarted": "Empezar" },
  it: { "nav.getStarted": "Inizia" },
  ar: {
    "nav.getStarted": "ابدأ الآن",
    "hero.subtitle":
      "يربط LetAIwork4u بين البرمجيات عالية الجودة وأتمتة الذكاء الاصطناعي وأفكار المنصات الجديدة. يتم بناء AnwaltSoft و beA4Outlook كمنتجات رئيسية لمكاتب المحاماة.",
    "spline.cardText":
      "يدعم LETAIWORK4U عملك بحلول ذكية للذكاء الاصطناعي تحول سير العمل وتزيد الإنتاجية.",
    "home.ecosystem.desc":
      "يتم بناء AnwaltSoft و beA4Outlook كمنتجات رئيسية. ويمكن للمنصات الأخرى أن تنمو بوضوح دون إعادة اختراع العلامة.",
    "home.discover.desc": "يوفر LETAIWORK4U كل ما تحتاجه لتطوير عملك بتقنية ذكاء اصطناعي حديثة.",
    "features.subtitle": "اكتشف لماذا يعد LETAIWORK4U شريك ذكاء اصطناعي مفضلا للشركات الحديثة.",
    "features.developers.title": "مصمم للمطورين",
    "features.developers.desc": "للمهندسين والمطورين والمبتكرين الذين يريدون استخدام الذكاء الاصطناعي في مشاريعهم.",
    "features.ease.title": "سهل الاستخدام",
    "features.ease.desc": "حلول ذكاء اصطناعي بديهية وسهلة الوصول للعمل اليومي.",
    "features.pricing.title": "أسعار شفافة",
    "features.pricing.desc": "أسعار واضحة ويمكن توقعها بدون رسوم مخفية.",
    "features.uptime.title": "توفر عال",
    "features.uptime.desc": "بنية قوية تساعد خدمات الذكاء الاصطناعي على البقاء متاحة.",
    "features.multi.title": "معمارية متعددة المستخدمين",
    "features.multi.desc": "مشاركة موارد الذكاء الاصطناعي بأمان مع صلاحيات حسب الأدوار.",
    "features.support.title": "دعم ذكاء اصطناعي 24/7",
    "features.support.desc": "مساعدة مستمرة عبر دعم مدعوم بالذكاء الاصطناعي وخبراء بشريين.",
    "features.improvement.title": "تحسين مستمر",
    "features.improvement.desc": "تتحسن النماذج بمرور الوقت لتقديم نتائج أفضل.",
    "features.custom.title": "حلول مخصصة",
    "features.custom.desc": "نخصص الذكاء الاصطناعي حسب قطاعك وعملياتك وأهدافك.",
    "capabilities.subtitle": "استكشف وظائف ذكاء اصطناعي مبتكرة عبر بطاقات تفاعلية.",
    "capabilities.automation.title": "أتمتة مدعومة بالذكاء الاصطناعي",
    "capabilities.automation.desc": "حسن سير العمل بأتمتة ذكية تتعلم وتتكيف.",
    "capabilities.analytics.title": "تحليلات متقدمة",
    "capabilities.analytics.desc": "حوّل بياناتك إلى رؤى قابلة للتنفيذ.",
    "capabilities.security.title": "تكامل آمن للذكاء الاصطناعي",
    "capabilities.security.desc": "أمان مؤسسي للتطبيقات ومعالجة البيانات.",
    "capabilities.custom.title": "حلول ذكاء اصطناعي مخصصة",
    "capabilities.custom.desc": "حلول مصممة لقطاعك وتحدياتك.",
    "capabilities.search.title": "بحث ذكي",
    "capabilities.search.desc": "اعثر على المعلومات ببحث يفهم السياق والنية.",
    "platform.anwaltsoft.eyebrow": "منصة LegalTech",
    "platform.anwaltsoft.summary": "نظام DMS وسير عمل للمكاتب القانونية ومستندات وعمليات قريبة من beA ودعم بالذكاء الاصطناعي.",
    "platform.bea4outlook.eyebrow": "منتج رئيسي",
    "platform.bea4outlook.summary": "رسائل beA وبريد Outlook في بيئة مألوفة مع ملفات hash وتسجيل دخول بالشهادة.",
    "testimonials.subtitle": "اقرأ كيف يعمل العملاء الراضون مع LETAIWORK4U.",
    "testimonials.0.role": "مدير التقنية في TechCorp",
    "testimonials.0.content": "غيّر LETAIWORK4U طريقة عمل فريقنا مع الذكاء الاصطناعي. الحلول بديهية والدعم قوي.",
    "testimonials.1.role": "مديرة منتج",
    "testimonials.1.content": "جربت منصات ذكاء اصطناعي كثيرة، ويمتاز LETAIWORK4U بسهولة الاستخدام وقوة الوظائف.",
    "testimonials.2.role": "مؤسس شركة ناشئة",
    "testimonials.2.content": "كنت أحتاج حلول ذكاء اصطناعي موثوقة وقابلة للتوسع، وقد تجاوز LETAIWORK4U توقعاتي.",
    "testimonials.3.role": "مديرة تسويق",
    "testimonials.3.content": "قدمت لنا تحليلات الذكاء الاصطناعي رؤى جديدة حسنت استراتيجيتنا.",
    "footer.desc": "علامة جامعة لتكامل الذكاء الاصطناعي وvoicebots وLegalTech والبرمجيات وتصميم الويب ومشاريع AI الجديدة.",
  },
  zh: {
    "nav.getStarted": "开始",
    "hero.subtitle": "LetAIwork4u 连接高品质软件、AI 自动化和新的平台构想。AnwaltSoft 与 beA4Outlook 正作为面向律所的旗舰产品打造。",
    "spline.cardText": "LETAIWORK4U 用智能 AI 解决方案推动业务发展，优化工作流并提升生产力。",
    "home.ecosystem.desc": "AnwaltSoft 与 beA4Outlook 正作为旗舰产品打造。更多平台可以清晰扩展，而不必每次重建品牌。",
    "home.discover.desc": "LETAIWORK4U 提供用现代 AI 技术转型业务所需的一切。",
    "features.subtitle": "了解为什么 LETAIWORK4U 是现代企业首选的 AI 合作伙伴。",
    "features.developers.title": "为开发者打造",
    "features.developers.desc": "面向希望在真实项目中使用 AI 的工程师、开发者和创新者。",
    "features.ease.title": "易于使用",
    "features.ease.desc": "直观、可访问、适合日常工作的 AI 解决方案。",
    "features.pricing.title": "透明价格",
    "features.pricing.desc": "清晰可预测的价格，没有隐藏费用。",
    "features.uptime.title": "高可用性",
    "features.uptime.desc": "稳健基础设施让 AI 服务保持可用。",
    "features.multi.title": "多租户架构",
    "features.multi.desc": "通过基于角色的访问控制安全共享 AI 资源。",
    "features.support.title": "24/7 AI 支持",
    "features.support.desc": "由 AI 支持系统和人工专家持续提供帮助。",
    "features.improvement.title": "持续改进",
    "features.improvement.desc": "模型不断学习改进，带来更好的结果。",
    "features.custom.title": "定制解决方案",
    "features.custom.desc": "根据行业、流程和目标定制 AI。",
    "capabilities.subtitle": "通过交互式卡片探索创新 AI 功能。",
    "capabilities.automation.title": "AI 自动化",
    "capabilities.automation.desc": "用会学习和适应的智能自动化优化工作流。",
    "capabilities.analytics.title": "高级分析",
    "capabilities.analytics.desc": "把数据转化为可执行洞察。",
    "capabilities.security.title": "安全 AI 集成",
    "capabilities.security.desc": "为 AI 实施和数据处理提供企业级安全。",
    "capabilities.custom.title": "定制 AI 方案",
    "capabilities.custom.desc": "为你的行业和挑战设计 AI。",
    "capabilities.search.title": "智能搜索",
    "capabilities.search.desc": "通过理解上下文和意图的搜索更快找到信息。",
    "platform.anwaltsoft.eyebrow": "LegalTech 平台",
    "platform.anwaltsoft.summary": "DMS、律所工作流、文档、beA 相关流程以及 AI 支持。",
    "platform.bea4outlook.eyebrow": "旗舰产品",
    "platform.bea4outlook.summary": "在熟悉的环境中处理 beA 消息和 Outlook 邮件，包含 hash 文件和证书登录。",
    "testimonials.subtitle": "看看满意客户如何使用 LETAIWORK4U。",
    "testimonials.0.role": "TechCorp CTO",
    "testimonials.0.content": "LETAIWORK4U 改变了我们团队使用 AI 的方式。方案直观，支持可靠。",
    "testimonials.1.role": "产品经理",
    "testimonials.1.content": "我尝试过许多 AI 平台，LETAIWORK4U 在易用性和能力上非常突出。",
    "testimonials.2.role": "创业公司创始人",
    "testimonials.2.content": "我需要可靠且可扩展的 AI 解决方案，LETAIWORK4U 超出了预期。",
    "testimonials.3.role": "营销总监",
    "testimonials.3.content": "AI 分析给了我们新的洞察，明显改善了营销策略。",
    "footer.desc": "AI 集成、voicebots、LegalTech、软件、网页设计和新 AI 项目的统一品牌。",
  },
  ja: {
    "nav.getStarted": "開始する",
    "hero.subtitle": "LetAIwork4u は高品質なソフトウェア、AI 自動化、新しいプラットフォーム構想を結びます。AnwaltSoft と beA4Outlook は法律事務所向けの旗艦製品として構築されています。",
    "spline.cardText": "LETAIWORK4U はインテリジェントな AI ソリューションで業務を前進させ、ワークフローと生産性を高めます。",
    "home.ecosystem.desc": "AnwaltSoft と beA4Outlook は旗艦製品として成長中です。追加プラットフォームもブランドを作り直さずに拡張できます。",
    "home.discover.desc": "LETAIWORK4U は先進的な AI 技術でビジネスを変革するための基盤を提供します。",
    "features.subtitle": "LETAIWORK4U が現代企業の AI パートナーとして選ばれる理由をご覧ください。",
    "features.developers.title": "開発者のために設計",
    "features.developers.desc": "実プロジェクトで AI を活用したいエンジニア、開発者、イノベーター向けです。",
    "features.ease.title": "使いやすさ",
    "features.ease.desc": "日常業務で使いやすい直感的な AI ソリューションです。",
    "features.pricing.title": "透明な料金",
    "features.pricing.desc": "隠れた費用のない、明確で予測可能な料金です。",
    "features.uptime.title": "高可用性",
    "features.uptime.desc": "堅牢なインフラにより AI サービスを安定して利用できます。",
    "features.multi.title": "マルチテナント構成",
    "features.multi.desc": "ロールベースのアクセス制御で AI リソースを安全に共有できます。",
    "features.support.title": "24時間 AI サポート",
    "features.support.desc": "AI 支援と専門家により継続的にサポートします。",
    "features.improvement.title": "継続的な改善",
    "features.improvement.desc": "モデルは学習を続け、より良い結果を提供します。",
    "features.custom.title": "カスタムソリューション",
    "features.custom.desc": "業界、プロセス、目標に合わせて AI を調整します。",
    "capabilities.subtitle": "インタラクティブなカードで革新的な AI 機能を探索できます。",
    "capabilities.automation.title": "AI 自動化",
    "capabilities.automation.desc": "学習し適応する自動化でワークフローを最適化します。",
    "capabilities.analytics.title": "高度な分析",
    "capabilities.analytics.desc": "データを実行可能な洞察に変えます。",
    "capabilities.security.title": "安全な AI 連携",
    "capabilities.security.desc": "AI 実装とデータ処理に企業レベルの安全性を提供します。",
    "capabilities.custom.title": "カスタム AI",
    "capabilities.custom.desc": "業界と課題に合わせて設計された AI ソリューションです。",
    "capabilities.search.title": "インテリジェント検索",
    "capabilities.search.desc": "文脈と意図を理解する検索で情報を見つけます。",
    "platform.anwaltsoft.eyebrow": "LegalTech プラットフォーム",
    "platform.anwaltsoft.summary": "DMS、法律事務所ワークフロー、文書、beA 関連プロセス、AI 支援。",
    "platform.bea4outlook.eyebrow": "旗艦製品",
    "platform.bea4outlook.summary": "beA メッセージと Outlook メールを、hash ファイルと証明書ログイン付きで扱えます。",
    "testimonials.subtitle": "満足している顧客が LETAIWORK4U をどう活用しているかをご覧ください。",
    "testimonials.0.role": "TechCorp CTO",
    "testimonials.0.content": "LETAIWORK4U は私たちの AI 活用を変えました。直感的でサポートも強力です。",
    "testimonials.1.role": "プロダクトマネージャー",
    "testimonials.1.content": "多くの AI プラットフォームを試しましたが、LETAIWORK4U は使いやすさと機能で際立っています。",
    "testimonials.2.role": "スタートアップ創業者",
    "testimonials.2.content": "信頼でき拡張可能な AI が必要でした。LETAIWORK4U は期待を超えました。",
    "testimonials.3.role": "マーケティング責任者",
    "testimonials.3.content": "AI 分析により新しい洞察を得て、マーケティング戦略を改善できました。",
    "footer.desc": "AI 連携、voicebots、LegalTech、ソフトウェア、Web デザイン、新しい AI プロジェクトの統合ブランド。",
  },
  th: {
    "nav.getStarted": "เริ่มต้น",
    "hero.subtitle": "LetAIwork4u เชื่อมซอฟต์แวร์คุณภาพสูง ระบบอัตโนมัติด้วย AI และแนวคิดแพลตฟอร์มใหม่ AnwaltSoft และ beA4Outlook ถูกพัฒนาเป็นผลิตภัณฑ์หลักสำหรับสำนักงานกฎหมาย.",
    "spline.cardText": "LETAIWORK4U ช่วยธุรกิจด้วยโซลูชัน AI อัจฉริยะที่ปรับปรุงเวิร์กโฟลว์และเพิ่มประสิทธิภาพ.",
    "home.ecosystem.desc": "AnwaltSoft และ beA4Outlook ถูกสร้างเป็นผลิตภัณฑ์หลัก แพลตฟอร์มอื่นสามารถเติบโตได้โดยไม่ต้องสร้างแบรนด์ใหม่ทุกครั้ง.",
    "home.discover.desc": "LETAIWORK4U ให้เครื่องมือที่จำเป็นในการพัฒนาธุรกิจด้วยเทคโนโลยี AI สมัยใหม่.",
    "features.subtitle": "ดูว่าทำไม LETAIWORK4U จึงเป็นพาร์ทเนอร์ AI ที่องค์กรสมัยใหม่เลือก.",
    "features.developers.title": "สร้างสำหรับนักพัฒนา",
    "features.developers.desc": "สำหรับทีมเทคนิคและผู้สร้างนวัตกรรมที่ต้องการใช้ AI ในโปรเจกต์จริง.",
    "features.ease.title": "ใช้งานง่าย",
    "features.ease.desc": "โซลูชัน AI ที่เข้าใจง่ายและเหมาะกับงานประจำวัน.",
    "features.pricing.title": "ราคาชัดเจน",
    "features.pricing.desc": "ราคาคาดการณ์ได้ ไม่มีค่าใช้จ่ายแอบแฝง.",
    "features.uptime.title": "พร้อมใช้งานสูง",
    "features.uptime.desc": "โครงสร้างพื้นฐานแข็งแรงเพื่อให้บริการ AI พร้อมใช้งาน.",
    "features.multi.title": "สถาปัตยกรรมหลายผู้ใช้",
    "features.multi.desc": "แบ่งปันทรัพยากร AI อย่างปลอดภัยด้วยสิทธิ์ตามบทบาท.",
    "features.support.title": "ซัพพอร์ต AI 24/7",
    "features.support.desc": "ช่วยเหลือต่อเนื่องด้วย AI และผู้เชี่ยวชาญ.",
    "features.improvement.title": "พัฒนาอย่างต่อเนื่อง",
    "features.improvement.desc": "โมเดลเรียนรู้และปรับปรุงผลลัพธ์ตลอดเวลา.",
    "features.custom.title": "โซลูชันเฉพาะ",
    "features.custom.desc": "ปรับ AI ให้เข้ากับธุรกิจ กระบวนการ และเป้าหมาย.",
    "capabilities.subtitle": "สำรวจฟังก์ชัน AI ผ่านการ์ดอินเทอร์แอคทีฟ.",
    "capabilities.automation.title": "ระบบอัตโนมัติด้วย AI",
    "capabilities.automation.desc": "ปรับปรุงเวิร์กโฟลว์ด้วยระบบอัตโนมัติอัจฉริยะ.",
    "capabilities.analytics.title": "การวิเคราะห์ขั้นสูง",
    "capabilities.analytics.desc": "เปลี่ยนข้อมูลเป็นข้อมูลเชิงลึกที่ใช้งานได้.",
    "capabilities.security.title": "การเชื่อมต่อ AI ที่ปลอดภัย",
    "capabilities.security.desc": "ความปลอดภัยระดับองค์กรสำหรับ AI และข้อมูล.",
    "capabilities.custom.title": "AI เฉพาะธุรกิจ",
    "capabilities.custom.desc": "AI ที่ออกแบบตามอุตสาหกรรมและความท้าทายของคุณ.",
    "capabilities.search.title": "ค้นหาอัจฉริยะ",
    "capabilities.search.desc": "ค้นหาข้อมูลด้วยระบบที่เข้าใจบริบทและเจตนา.",
    "platform.anwaltsoft.eyebrow": "แพลตฟอร์ม LegalTech",
    "platform.anwaltsoft.summary": "DMS เวิร์กโฟลว์สำนักงานกฎหมาย เอกสาร กระบวนการใกล้ beA และการสนับสนุนด้วย AI.",
    "platform.bea4outlook.eyebrow": "ผลิตภัณฑ์หลัก",
    "platform.bea4outlook.summary": "ข้อความ beA และอีเมล Outlook ในสภาพแวดล้อมที่คุ้นเคย พร้อม hash files และ certificate login.",
    "testimonials.subtitle": "อ่านว่าลูกค้าพึงพอใจใช้งาน LETAIWORK4U อย่างไร.",
    "testimonials.0.role": "CTO ที่ TechCorp",
    "testimonials.0.content": "LETAIWORK4U เปลี่ยนวิธีที่ทีมเราใช้ AI ใช้งานง่ายและซัพพอร์ตดีมาก.",
    "testimonials.1.role": "Product Manager",
    "testimonials.1.content": "ฉันลองหลายแพลตฟอร์ม AI แล้ว LETAIWORK4U เด่นเรื่องความง่ายและความสามารถ.",
    "testimonials.2.role": "ผู้ก่อตั้งสตาร์ทอัพ",
    "testimonials.2.content": "ฉันต้องการ AI ที่น่าเชื่อถือและขยายได้ LETAIWORK4U ทำได้เกินคาด.",
    "testimonials.3.role": "ผู้อำนวยการการตลาด",
    "testimonials.3.content": "AI analytics ให้ข้อมูลใหม่ที่ช่วยปรับกลยุทธ์การตลาด.",
    "footer.desc": "แบรนด์หลักสำหรับ AI integration, voicebots, LegalTech, software, webdesign และโปรเจกต์ AI ใหม่.",
  },
  fi: {
    "nav.getStarted": "Aloita",
    "hero.subtitle": "LetAIwork4u yhdistaa laadukkaan ohjelmiston, AI-automaation ja uudet alustakonseptit. AnwaltSoft ja beA4Outlook rakennetaan lippulaivatuotteiksi lakitoimistoille.",
    "spline.cardText": "LETAIWORK4U vie liiketoimintaa eteenpain alykkäillä AI-ratkaisuilla, jotka parantavat tyonkulkuja ja tuottavuutta.",
    "home.ecosystem.desc": "AnwaltSoft ja beA4Outlook rakennetaan lippulaivatuotteiksi. Muut alustat voivat kasvaa selkeasti ilman brändin uudelleenluontia.",
    "home.discover.desc": "LETAIWORK4U tarjoaa kaiken, mita tarvitset liiketoiminnan kehittamiseen modernilla AI-teknologialla.",
    "features.subtitle": "Tutustu siihen, miksi LETAIWORK4U on modernien yritysten suosima AI-kumppani.",
    "features.developers.title": "Rakennettu kehittajille",
    "features.developers.desc": "Teknisille tiimeille ja innovaattoreille, jotka haluavat kayttaa AI:ta oikeissa projekteissa.",
    "features.ease.title": "Helppo kayttaa",
    "features.ease.desc": "Intuitiivisia AI-ratkaisuja paivittaiseen tyohon.",
    "features.pricing.title": "Läpinäkyva hinnoittelu",
    "features.pricing.desc": "Selkea ja ennakoitava hinnoittelu ilman piilokuluja.",
    "features.uptime.title": "Korkea kaytettavyys",
    "features.uptime.desc": "Vahva infrastruktuuri pitaa AI-palvelut saatavilla.",
    "features.multi.title": "Moniasiakasarkkitehtuuri",
    "features.multi.desc": "Jaa AI-resursseja turvallisesti roolipohjaisella paasylla.",
    "features.support.title": "AI-tuki 24/7",
    "features.support.desc": "Jatkuvaa tukea AI:n ja asiantuntijoiden avulla.",
    "features.improvement.title": "Jatkuva parantaminen",
    "features.improvement.desc": "Mallit oppivat ja tuottavat parempia tuloksia ajan myota.",
    "features.custom.title": "Räätälöidyt ratkaisut",
    "features.custom.desc": "Mukautamme AI:n toimialaasi, prosesseihisi ja tavoitteisiisi.",
    "capabilities.subtitle": "Tutustu innovatiivisiin AI-toimintoihin interaktiivisilla korteilla.",
    "capabilities.automation.title": "AI-automaatio",
    "capabilities.automation.desc": "Optimoi tyonkulut alykkäällä automaatiolla.",
    "capabilities.analytics.title": "Edistynyt analytiikka",
    "capabilities.analytics.desc": "Muunna data toiminnallisiksi oivalluksiksi.",
    "capabilities.security.title": "Turvallinen AI-integraatio",
    "capabilities.security.desc": "Yritystason turvallisuus AI-toteutuksiin ja dataan.",
    "capabilities.custom.title": "Räätälöity AI",
    "capabilities.custom.desc": "AI-ratkaisuja juuri sinun toimialallesi ja haasteisiisi.",
    "capabilities.search.title": "Älykäs haku",
    "capabilities.search.desc": "Loyda tietoa haulla, joka ymmartaa kontekstin ja tarkoituksen.",
    "platform.anwaltsoft.eyebrow": "LegalTech-alusta",
    "platform.anwaltsoft.summary": "DMS, lakitoimiston tyonkulut, dokumentit, beA-laheiset prosessit ja AI-tuki.",
    "platform.bea4outlook.eyebrow": "Lippulaivatuote",
    "platform.bea4outlook.summary": "beA-viestit ja Outlook-sahkopostit tutussa ymparistossa, hash-tiedostoilla ja varmennekirjautumisella.",
    "testimonials.subtitle": "Lue, miten tyytyvaiset asiakkaat kayttavat LETAIWORK4U:ta.",
    "testimonials.0.role": "CTO, TechCorp",
    "testimonials.0.content": "LETAIWORK4U muutti tapamme tyoskennella AI:n kanssa. Ratkaisut ovat intuitiivisia ja tuki vahvaa.",
    "testimonials.1.role": "Tuotepaallikko",
    "testimonials.1.content": "Olen kokeillut monia AI-alustoja; LETAIWORK4U erottuu helppokayttoisyydellaan ja teholtaan.",
    "testimonials.2.role": "Startup-perustaja",
    "testimonials.2.content": "Tarvitsin luotettavia ja skaalautuvia AI-ratkaisuja. LETAIWORK4U ylitti odotukseni.",
    "testimonials.3.role": "Markkinointijohtaja",
    "testimonials.3.content": "AI-analytiikka antoi meille uusia oivalluksia ja paransi strategiaamme.",
    "footer.desc": "Kattobrandi AI-integraatiolle, voiceboteille, LegalTechille, ohjelmistoille, webdesignille ja uusille AI-projekteille.",
  },
  nl: {
    "nav.getStarted": "Aan de slag",
    "hero.subtitle": "LetAIwork4u verbindt hoogwaardige software, AI-automatisering en nieuwe platformideeën. AnwaltSoft en beA4Outlook worden gebouwd als vlaggenschipproducten voor advocatenkantoren.",
    "spline.cardText": "LETAIWORK4U brengt je bedrijf vooruit met intelligente AI-oplossingen die workflows verbeteren en productiviteit verhogen.",
    "home.ecosystem.desc": "AnwaltSoft en beA4Outlook worden vlaggenschipproducten. Andere platforms kunnen helder groeien zonder het merk telkens opnieuw uit te vinden.",
    "home.discover.desc": "LETAIWORK4U biedt alles om je bedrijf met moderne AI-technologie te transformeren.",
    "features.subtitle": "Ontdek waarom LETAIWORK4U een favoriete AI-partner is voor moderne bedrijven.",
    "features.developers.title": "Gebouwd voor ontwikkelaars",
    "features.developers.desc": "Voor technische teams en vernieuwers die AI in echte projecten willen gebruiken.",
    "features.ease.title": "Eenvoudig in gebruik",
    "features.ease.desc": "Intuitieve AI-oplossingen voor dagelijks werk.",
    "features.pricing.title": "Transparante prijzen",
    "features.pricing.desc": "Duidelijke, voorspelbare prijzen zonder verborgen kosten.",
    "features.uptime.title": "Hoge beschikbaarheid",
    "features.uptime.desc": "Sterke infrastructuur houdt AI-diensten beschikbaar.",
    "features.multi.title": "Multi-tenant architectuur",
    "features.multi.desc": "Deel AI-resources veilig met rolgebaseerde toegang.",
    "features.support.title": "AI-support 24/7",
    "features.support.desc": "Doorlopende hulp met AI-ondersteuning en menselijke experts.",
    "features.improvement.title": "Continue verbetering",
    "features.improvement.desc": "Modellen leren en leveren met de tijd betere resultaten.",
    "features.custom.title": "Maatwerkoplossingen",
    "features.custom.desc": "We stemmen AI af op je sector, processen en doelen.",
    "capabilities.subtitle": "Ontdek innovatieve AI-functies met interactieve kaarten.",
    "capabilities.automation.title": "AI-automatisering",
    "capabilities.automation.desc": "Optimaliseer workflows met intelligente automatisering.",
    "capabilities.analytics.title": "Geavanceerde analytics",
    "capabilities.analytics.desc": "Zet data om in bruikbare inzichten.",
    "capabilities.security.title": "Veilige AI-integratie",
    "capabilities.security.desc": "Enterprise-beveiliging voor AI-implementaties en data.",
    "capabilities.custom.title": "AI op maat",
    "capabilities.custom.desc": "AI ontworpen voor jouw sector en uitdagingen.",
    "capabilities.search.title": "Intelligente zoekfunctie",
    "capabilities.search.desc": "Vind informatie met zoektechnologie die context en intentie begrijpt.",
    "platform.anwaltsoft.eyebrow": "LegalTech-platform",
    "platform.anwaltsoft.summary": "DMS, kantoorworkflows, documenten, beA-processen en AI-ondersteuning.",
    "platform.bea4outlook.eyebrow": "Vlaggenschipproduct",
    "platform.bea4outlook.summary": "beA-berichten en Outlook-mail in een vertrouwde omgeving, met hashbestanden en certificaatlogin.",
    "testimonials.subtitle": "Lees hoe tevreden klanten met LETAIWORK4U werken.",
    "testimonials.0.role": "CTO bij TechCorp",
    "testimonials.0.content": "LETAIWORK4U veranderde hoe ons team met AI werkt. De oplossingen zijn intuitief en de ondersteuning is sterk.",
    "testimonials.1.role": "Productmanager",
    "testimonials.1.content": "Ik heb veel AI-platforms geprobeerd; LETAIWORK4U valt op door gebruiksgemak en krachtige functies.",
    "testimonials.2.role": "Startup-oprichter",
    "testimonials.2.content": "Ik had betrouwbare en schaalbare AI nodig. LETAIWORK4U overtrof mijn verwachtingen.",
    "testimonials.3.role": "Marketingdirecteur",
    "testimonials.3.content": "AI-analytics gaf ons nieuwe inzichten en verbeterde onze strategie.",
    "footer.desc": "Overkoepelend merk voor AI-integratie, voicebots, LegalTech, software, webdesign en nieuwe AI-projecten.",
  },
  fr: {
    "nav.getStarted": "Commencer",
    "hero.subtitle": "LetAIwork4u relie logiciels haut de gamme, automatisation IA et nouvelles idees de plateforme. AnwaltSoft et beA4Outlook sont construits comme produits phares pour les cabinets.",
    "spline.cardText": "LETAIWORK4U fait avancer votre entreprise avec des solutions IA intelligentes qui transforment les flux de travail et la productivite.",
    "home.ecosystem.desc": "AnwaltSoft et beA4Outlook sont developpes comme produits phares. D'autres plateformes peuvent grandir clairement sans reinventer la marque.",
    "home.discover.desc": "LETAIWORK4U fournit ce qu'il faut pour transformer votre entreprise avec une technologie IA moderne.",
    "features.subtitle": "Decouvrez pourquoi LETAIWORK4U est un partenaire IA privilegie pour les entreprises modernes.",
    "features.developers.title": "Concu pour les developpeurs",
    "features.developers.desc": "Pour les equipes techniques et innovateurs qui veulent utiliser l'IA dans des projets reels.",
    "features.ease.title": "Facile a utiliser",
    "features.ease.desc": "Des solutions IA intuitives et accessibles pour le travail quotidien.",
    "features.pricing.title": "Tarification transparente",
    "features.pricing.desc": "Des prix clairs et previsibles, sans frais caches.",
    "features.uptime.title": "Haute disponibilite",
    "features.uptime.desc": "Une infrastructure robuste garde vos services IA disponibles.",
    "features.multi.title": "Architecture multi-tenant",
    "features.multi.desc": "Partagez les ressources IA en securite avec des droits par role.",
    "features.support.title": "Support IA 24/7",
    "features.support.desc": "Une aide continue avec support IA et experts humains.",
    "features.improvement.title": "Amelioration continue",
    "features.improvement.desc": "Les modeles apprennent et ameliorent les resultats avec le temps.",
    "features.custom.title": "Solutions sur mesure",
    "features.custom.desc": "Nous adaptons l'IA a votre secteur, vos processus et vos objectifs.",
    "capabilities.subtitle": "Explorez des fonctions IA innovantes avec des cartes interactives.",
    "capabilities.automation.title": "Automatisation IA",
    "capabilities.automation.desc": "Optimisez vos flux de travail avec une automatisation intelligente.",
    "capabilities.analytics.title": "Analytique avancee",
    "capabilities.analytics.desc": "Transformez vos donnees en informations exploitables.",
    "capabilities.security.title": "Integration IA securisee",
    "capabilities.security.desc": "Securite entreprise pour vos implementations IA et vos donnees.",
    "capabilities.custom.title": "Solutions IA personnalisees",
    "capabilities.custom.desc": "Une IA concue pour votre secteur et vos defis.",
    "capabilities.search.title": "Recherche intelligente",
    "capabilities.search.desc": "Trouvez l'information avec une recherche qui comprend contexte et intention.",
    "platform.anwaltsoft.eyebrow": "Plateforme LegalTech",
    "platform.anwaltsoft.summary": "DMS, workflows de cabinet, documents, processus proches de beA et support IA.",
    "platform.bea4outlook.eyebrow": "Produit phare",
    "platform.bea4outlook.summary": "Messages beA et e-mails Outlook dans un environnement familier, avec hash et connexion certificat.",
    "testimonials.subtitle": "Lisez comment des clients satisfaits travaillent avec LETAIWORK4U.",
    "testimonials.0.role": "CTO chez TechCorp",
    "testimonials.0.content": "LETAIWORK4U a change notre facon de travailler avec l'IA. Les solutions sont intuitives et le support est solide.",
    "testimonials.1.role": "Product Manager",
    "testimonials.1.content": "J'ai teste beaucoup de plateformes IA; LETAIWORK4U se distingue par sa simplicite et sa puissance.",
    "testimonials.2.role": "Fondateur de startup",
    "testimonials.2.content": "J'avais besoin d'une IA fiable et scalable. LETAIWORK4U a depasse mes attentes.",
    "testimonials.3.role": "Directrice marketing",
    "testimonials.3.content": "Les analytics IA nous ont donne de nouveaux insights et ont ameliore notre strategie.",
    "footer.desc": "Marque ombrelle pour integration IA, voicebots, LegalTech, logiciel, webdesign et nouveaux projets IA.",
  },
  sv: {
    "nav.getStarted": "Kom igang",
    "hero.subtitle": "LetAIwork4u kopplar samman premiumprogramvara, AI-automatisering och nya plattformsidéer. AnwaltSoft och beA4Outlook byggs som flaggskeppsprodukter for advokatbyraer.",
    "spline.cardText": "LETAIWORK4U driver verksamheten framat med intelligenta AI-loesningar som forbatttar arbetsfloden och produktiviteten.",
    "home.ecosystem.desc": "AnwaltSoft och beA4Outlook byggs som flaggskeppsprodukter. Fler plattformar kan vaxa tydligt utan att varumarket skapas om.",
    "home.discover.desc": "LETAIWORK4U ger allt du behover for att utveckla verksamheten med modern AI-teknik.",
    "features.subtitle": "Se varfor LETAIWORK4U ar en foredragen AI-partner for moderna foretag.",
    "features.developers.title": "Byggt for utvecklare",
    "features.developers.desc": "For tekniska team och innovatorer som vill anvanda AI i verkliga projekt.",
    "features.ease.title": "Latt att anvanda",
    "features.ease.desc": "Intuitiva AI-loesningar for dagligt arbete.",
    "features.pricing.title": "Transparent prissattning",
    "features.pricing.desc": "Tydliga och forutsagbara priser utan dolda avgifter.",
    "features.uptime.title": "Hog tillganglighet",
    "features.uptime.desc": "Robust infrastruktur haller AI-tjansterna tillgangliga.",
    "features.multi.title": "Multi-tenant arkitektur",
    "features.multi.desc": "Dela AI-resurser sakert med rollbaserad atkomst.",
    "features.support.title": "AI-support 24/7",
    "features.support.desc": "Kontinuerlig hjalp med AI-stod och manskliga experter.",
    "features.improvement.title": "Kontinuerlig forbattrning",
    "features.improvement.desc": "Modellerna lar sig och ger battre resultat over tid.",
    "features.custom.title": "Anpassade loesningar",
    "features.custom.desc": "Vi anpassar AI till din bransch, dina processer och mal.",
    "capabilities.subtitle": "Utforska innovativa AI-funktioner med interaktiva kort.",
    "capabilities.automation.title": "AI-automatisering",
    "capabilities.automation.desc": "Optimera arbetsfloden med intelligent automatisering.",
    "capabilities.analytics.title": "Avancerad analys",
    "capabilities.analytics.desc": "Gor data till praktiska insikter.",
    "capabilities.security.title": "Saker AI-integration",
    "capabilities.security.desc": "Foretagsklassad sakerhet for AI och data.",
    "capabilities.custom.title": "Anpassad AI",
    "capabilities.custom.desc": "AI byggd for din bransch och dina utmaningar.",
    "capabilities.search.title": "Intelligent sokning",
    "capabilities.search.desc": "Hitta information med sokning som forstar kontext och avsikt.",
    "platform.anwaltsoft.eyebrow": "LegalTech-plattform",
    "platform.anwaltsoft.summary": "DMS, advokatbyrafloden, dokument, beA-nara processer och AI-stod.",
    "platform.bea4outlook.eyebrow": "Flaggskeppsprodukt",
    "platform.bea4outlook.summary": "beA-meddelanden och Outlook-mail i en bekant miljo, med hashfiler och certifikatinloggning.",
    "testimonials.subtitle": "Las hur nojda kunder arbetar med LETAIWORK4U.",
    "testimonials.0.role": "CTO pa TechCorp",
    "testimonials.0.content": "LETAIWORK4U forandrade hur vart team arbetar med AI. Loesningarna ar intuitiva och supporten stark.",
    "testimonials.1.role": "Produktchef",
    "testimonials.1.content": "Jag har testat manga AI-plattformar; LETAIWORK4U sticker ut genom enkelhet och kraft.",
    "testimonials.2.role": "Startup-grundare",
    "testimonials.2.content": "Jag behovde tillforlitlig och skalbar AI. LETAIWORK4U overtraff mina forvantningar.",
    "testimonials.3.role": "Marknadschef",
    "testimonials.3.content": "AI-analysen gav nya insikter och forbattrade var strategi.",
    "footer.desc": "Paraplyvarumarke for AI-integration, voicebots, LegalTech, software, webdesign och nya AI-projekt.",
  },
  pt: {
    "nav.getStarted": "Comecar",
    "hero.subtitle": "LetAIwork4u conecta software premium, automacao com IA e novas ideias de plataforma. AnwaltSoft e beA4Outlook sao produtos principais para escritorios de advocacia.",
    "spline.cardText": "LETAIWORK4U impulsiona sua empresa com solucoes inteligentes de IA que melhoram fluxos de trabalho e produtividade.",
    "home.ecosystem.desc": "AnwaltSoft e beA4Outlook sao desenvolvidos como produtos principais. Outras plataformas podem crescer sem reinventar a marca.",
    "home.discover.desc": "LETAIWORK4U oferece tudo para transformar seu negocio com tecnologia moderna de IA.",
    "features.subtitle": "Veja por que LETAIWORK4U e um parceiro de IA preferido por empresas modernas.",
    "features.developers.title": "Feito para desenvolvedores",
    "features.developers.desc": "Para equipes tecnicas e inovadores que querem usar IA em projetos reais.",
    "features.ease.title": "Facil de usar",
    "features.ease.desc": "Solucoes de IA intuitivas para o trabalho diario.",
    "features.pricing.title": "Precos transparentes",
    "features.pricing.desc": "Precos claros e previsiveis, sem taxas escondidas.",
    "features.uptime.title": "Alta disponibilidade",
    "features.uptime.desc": "Infraestrutura robusta para manter servicos de IA disponiveis.",
    "features.multi.title": "Arquitetura multi-tenant",
    "features.multi.desc": "Compartilhe recursos de IA com seguranca e acesso por funcoes.",
    "features.support.title": "Suporte IA 24/7",
    "features.support.desc": "Ajuda continua com suporte de IA e especialistas humanos.",
    "features.improvement.title": "Melhoria continua",
    "features.improvement.desc": "Modelos aprendem e melhoram resultados ao longo do tempo.",
    "features.custom.title": "Solucoes sob medida",
    "features.custom.desc": "Adaptamos IA ao seu setor, processos e objetivos.",
    "capabilities.subtitle": "Explore funcoes inovadoras de IA com cards interativos.",
    "capabilities.automation.title": "Automacao com IA",
    "capabilities.automation.desc": "Otimize fluxos de trabalho com automacao inteligente.",
    "capabilities.analytics.title": "Analise avancada",
    "capabilities.analytics.desc": "Transforme dados em insights acionaveis.",
    "capabilities.security.title": "Integracao segura de IA",
    "capabilities.security.desc": "Seguranca empresarial para IA e dados.",
    "capabilities.custom.title": "IA personalizada",
    "capabilities.custom.desc": "IA desenhada para seu setor e desafios.",
    "capabilities.search.title": "Busca inteligente",
    "capabilities.search.desc": "Encontre informacoes com busca que entende contexto e intencao.",
    "platform.anwaltsoft.eyebrow": "Plataforma LegalTech",
    "platform.anwaltsoft.summary": "DMS, fluxos de escritorio juridico, documentos, processos proximos ao beA e apoio de IA.",
    "platform.bea4outlook.eyebrow": "Produto principal",
    "platform.bea4outlook.summary": "Mensagens beA e e-mails Outlook em um ambiente familiar, com hash e login por certificado.",
    "testimonials.subtitle": "Leia como clientes satisfeitos trabalham com LETAIWORK4U.",
    "testimonials.0.role": "CTO na TechCorp",
    "testimonials.0.content": "LETAIWORK4U mudou como nossa equipe trabalha com IA. As solucoes sao intuitivas e o suporte e forte.",
    "testimonials.1.role": "Product Manager",
    "testimonials.1.content": "Testei muitas plataformas de IA; LETAIWORK4U se destaca pela facilidade e potencia.",
    "testimonials.2.role": "Fundador de startup",
    "testimonials.2.content": "Eu precisava de IA confiavel e escalavel. LETAIWORK4U superou minhas expectativas.",
    "testimonials.3.role": "Diretora de marketing",
    "testimonials.3.content": "A analise com IA trouxe novos insights e melhorou nossa estrategia.",
    "footer.desc": "Marca guarda-chuva para integracao de IA, voicebots, LegalTech, software, webdesign e novos projetos.",
  },
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("de")
  const currentLanguage = languageOptions.find((option) => option.code === language) ?? languageOptions[1]
  const fallbackTranslations = language === "de" || language === "de-CH" ? defaultTranslations : translations.en ?? defaultTranslations
  const dictionary = {
    ...fallbackTranslations,
    ...(translations[language] ?? {}),
    ...(supplementalTranslations[language] ?? {}),
    ...(expandedHomepageTranslations[language] ?? {}),
  }

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem("letaiwork4u-language") as Language | null
    if (savedLanguage && languageOptions.some((option) => option.code === savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    window.localStorage.setItem("letaiwork4u-language", language)
    document.documentElement.lang = language
    document.documentElement.dir = currentLanguage.dir
  }, [currentLanguage.dir, language])

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      currentLanguage,
      isRTL: currentLanguage.dir === "rtl",
      t: (key: string) => dictionary[key] ?? defaultTranslations[key] ?? key,
    }),
    [currentLanguage, dictionary, language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
