"use client"

import { createContext, useContext, useEffect, useMemo, useState } from "react"

export type Language =
  | "en"
  | "de"
  | "es"
  | "it"
  | "ar"
  | "zh"
  | "ja"
  | "th"
  | "fi"
  | "nl"
  | "de-CH"
  | "fr"
  | "sv"
  | "pt"

export type LanguageOption = {
  code: Language
  shortLabel: string
  label: string
  localeName: string
  dir: "ltr" | "rtl"
}

export const languageOptions: LanguageOption[] = [
  { code: "en", shortLabel: "EN", label: "English", localeName: "English", dir: "ltr" },
  { code: "de", shortLabel: "DE", label: "Deutsch", localeName: "Deutsch", dir: "ltr" },
  { code: "es", shortLabel: "ES", label: "Spanisch", localeName: "Espanol", dir: "ltr" },
  { code: "it", shortLabel: "IT", label: "Italienisch", localeName: "Italiano", dir: "ltr" },
  { code: "ar", shortLabel: "AR", label: "Arabisch", localeName: "Arabic", dir: "rtl" },
  { code: "zh", shortLabel: "ZH", label: "Chinesisch", localeName: "Chinese", dir: "ltr" },
  { code: "ja", shortLabel: "JA", label: "Japanisch", localeName: "Japanese", dir: "ltr" },
  { code: "th", shortLabel: "TH", label: "Thailaendisch", localeName: "Thai", dir: "ltr" },
  { code: "fi", shortLabel: "FI", label: "Finnisch", localeName: "Suomi", dir: "ltr" },
  { code: "nl", shortLabel: "NL", label: "Niederlaendisch", localeName: "Nederlands", dir: "ltr" },
  { code: "de-CH", shortLabel: "CH", label: "Schweizer Deutsch", localeName: "Schweizer Deutsch", dir: "ltr" },
  { code: "fr", shortLabel: "FR", label: "Franzoesisch", localeName: "Francais", dir: "ltr" },
  { code: "sv", shortLabel: "SV", label: "Schwedisch", localeName: "Svenska", dir: "ltr" },
  { code: "pt", shortLabel: "PT", label: "Portugiesisch", localeName: "Portugues", dir: "ltr" },
]

type LanguageContextValue = {
  language: Language
  setLanguage: (language: Language) => void
  currentLanguage: LanguageOption
  isRTL: boolean
  t: (key: string) => string
}

const defaultTranslations: Record<string, string> = {
  "nav.home": "Home",
  "nav.platforms": "Plattformen",
  "nav.products": "Produkte",
  "nav.solutions": "Loesungen",
  "nav.news": "KI Feed",
  "nav.pricing": "Preise",
  "nav.contact": "Kontakt",
  "nav.voiceAgent": "Try our AI Voice Agent",
  "nav.language": "Sprache",
  "hero.word.legaltech": "LegalTech",
  "hero.word.voicebots": "Voicebots",
  "hero.word.robotics": "Robotik",
  "hero.word.realEstate": "Immobilien",
  "hero.word.aviation": "Aviation",
  "hero.titleSuffix": "unter einer starken AI-Marke.",
  "hero.subtitle":
    "LetAIwork4u verbindet hochwertige Software, KI-Automation und neue Plattformideen. AnwaltSoft und beA4Outlook werden als Premium-Flagship fuer Kanzleien aufgebaut.",
  "hero.cta.platforms": "Plattformen ansehen",
  "hero.cta.anwaltsoft": "AnwaltSoft entdecken",
  "spline.title": "LETAIWORK4U Interactive Experience",
  "spline.subtitle": "Explore our AI-powered platform with immersive 3D visualizations",
  "spline.cardTitle": "AI-Powered Solutions",
  "spline.cardText":
    "LETAIWORK4U bringt Ihr Unternehmen mit intelligenten KI-Loesungen voran. Schaffen Sie immersive Erlebnisse, die Workflows transformieren und Produktivitaet steigern.",
  "home.ecosystem.eyebrow": "LetAIwork4u Oekosystem",
  "home.ecosystem.title": "Eine Dachmarke fuer KI, LegalTech, Voicebots, Robotik und neue Plattformideen.",
  "home.ecosystem.desc":
    "AnwaltSoft und beA4Outlook werden als Flagship-Produkte aufgebaut. Weitere Plattformen koennen sauber wachsen, ohne die Marke jedes Mal neu zu erfinden.",
  "home.ecosystem.cta": "Alle Plattformen ansehen",
  "home.discover.title": "Discover our AI-powered solutions",
  "home.discover.desc":
    "LETAIWORK4U provides everything you need to transform your business with cutting-edge AI technology.",
  "animated.prefix": "Ihr",
  "animated.suffix": "verdient bessere Werkzeuge",
  "animated.word.business": "Unternehmen",
  "animated.word.team": "Team",
  "animated.word.workflow": "Workflow",
  "animated.word.productivity": "Produktivitaet",
  "animated.word.strategy": "KI-Strategie",
  "animated.word.transformation": "digitale Transformation",
  "animated.word.automation": "Automatisierung",
  "animated.word.analytics": "Analytics",
  "features.title": "AI Solutions that set us apart",
  "features.subtitle": "Discover why LETAIWORK4U is the preferred AI partner for businesses worldwide",
  "features.developers.title": "Gebaut fuer Entwickler",
  "features.developers.desc": "Fuer Engineers, Entwickler und Innovatoren, die KI in ihren Projekten nutzen wollen.",
  "features.ease.title": "Einfach nutzbar",
  "features.ease.desc": "Unsere KI-Loesungen sind intuitiv, zugaenglich und brauchen wenig technisches Vorwissen.",
  "features.pricing.title": "Transparente Preise",
  "features.pricing.desc": "Klare, planbare Preise ohne versteckte Gebuehren. Sie zahlen nur, was Sie nutzen.",
  "features.uptime.title": "99.9% Uptime Garantie",
  "features.uptime.desc": "Unsere robuste Infrastruktur sorgt dafuer, dass Ihre KI-Services verfuegbar bleiben.",
  "features.multi.title": "Multi-Tenant Architektur",
  "features.multi.desc": "KI-Ressourcen sicher im Unternehmen teilen, mit rollenbasiertem Zugriff.",
  "features.support.title": "24/7 AI Support",
  "features.support.desc": "Hilfe jederzeit durch KI-gestuetzten Support und menschliche Experten.",
  "features.improvement.title": "Kontinuierliche Verbesserung",
  "features.improvement.desc": "Unsere KI-Modelle lernen und verbessern sich, damit Ergebnisse mit der Zeit besser werden.",
  "features.custom.title": "Individuelle Loesungen",
  "features.custom.desc": "Wir passen KI-Loesungen an Ihre Branche, Prozesse und Ziele an.",
  "capabilities.title": "AI-Powered Capabilities",
  "capabilities.subtitle": "Discover our innovative AI features with interactive glowing cards",
  "capabilities.automation.title": "KI-gestuetzte Automatisierung",
  "capabilities.automation.desc": "Optimieren Sie Workflows mit intelligenter Automatisierung, die lernt und sich anpasst.",
  "capabilities.analytics.title": "Advanced Analytics",
  "capabilities.analytics.desc": "Gewinnen Sie verwertbare Erkenntnisse aus Daten mit leistungsstarken KI-Analytics.",
  "capabilities.security.title": "Sichere KI-Integration",
  "capabilities.security.desc": "Enterprise-Sicherheit fuer KI-Implementierung und Datenverarbeitung.",
  "capabilities.custom.title": "Custom AI Solutions",
  "capabilities.custom.desc": "Massgeschneiderte KI-Loesungen fuer Ihre Branche und Ihre Herausforderungen.",
  "capabilities.search.title": "Intelligente Suche",
  "capabilities.search.desc": "Finden Sie schneller, was Sie brauchen, mit KI-Suche, die Kontext und Absicht versteht.",
  "testimonials.title": "What Our Customers Say",
  "testimonials.subtitle": "Don't just take our word for it - hear from some of our satisfied customers",
  "footer.desc": "Muttermarke fuer KI-Integration, Voicebots, LegalTech, Software, Webdesign und neue AI-Projekte.",
  "footer.ecosystem": "Oekosystem",
  "contact.title": "Kontakt",
  "contact.subtitle": "Sprechen wir ueber KI, Automatisierung, Voicebots oder LegalTech.",
  "contact.callUs": "Anrufen",
  "contact.callUsDesc": "Direkter Kontakt fuer Beratung und Projektstart.",
  "contact.emailUs": "E-Mail",
  "contact.emailUsDesc": "Schreiben Sie uns Ihre Idee oder Anfrage.",
  "contact.consultation": "Beratung",
  "contact.consultationDesc": "Kostenloser Ersttermin fuer passende naechste Schritte.",
  "contact.formBelow": "Formular unten nutzen",
  "contact.sendMessage": "Nachricht senden",
  "contact.messageSent": "Nachricht gesendet",
  "contact.thankYou": "Danke. Wir melden uns zeitnah.",
  "contact.fullName": "Name",
  "contact.email": "E-Mail",
  "contact.company": "Firma",
  "contact.phone": "Telefon",
  "contact.productInterest": "Interesse",
  "contact.message": "Nachricht",
  "contact.submit": "Anfrage absenden",
  "contact.whyChoose": "Warum LetAIwork4u",
  "contact.cuttingEdge": "Moderne KI",
  "contact.cuttingEdgeDesc": "Praxisnahe Automatisierung statt Buzzwords.",
  "contact.expertTeam": "Umsetzung aus einer Hand",
  "contact.expertTeamDesc": "Strategie, Design, Software und Integration.",
  "contact.provenResults": "Fokus auf Ergebnis",
  "contact.provenResultsDesc": "Workflows, die Zeit sparen und messbar helfen.",
  "products.title": "Produkte",
  "products.subtitle": "KI-Produkte, Automatisierung und LegalTech aus dem LetAIwork4u Oekosystem.",
  "products.enterpriseAIChatbot.title": "Enterprise AI Chatbot",
  "products.enterpriseAIChatbot.description": "KI-Chatbot fuer Support, Vertrieb und interne Wissensprozesse.",
  "products.intelligentVoiceAssistant.title": "Intelligent Voice Assistant",
  "products.intelligentVoiceAssistant.description": "Telefon- und Voicebot-Automatisierung mit Weiterleitung und Terminlogik.",
  "products.businessProcessAutomation.title": "Business Process Automation",
  "products.businessProcessAutomation.description": "Automatisierte Workflows fuer wiederkehrende Aufgaben und Dokumente.",
  "products.predictiveAnalyticsPlatform.title": "Predictive Analytics Platform",
  "products.predictiveAnalyticsPlatform.description": "Aus Daten bessere Entscheidungen, Prognosen und Dashboards machen.",
  "products.customAIDevelopment.title": "Custom AI Development",
  "products.customAIDevelopment.description": "Massgeschneiderte KI-Loesungen fuer spezielle Prozesse.",
  "products.aiImplementationServices.title": "AI Implementation Services",
  "products.aiImplementationServices.description": "Beratung, Einfuehrung, Schulung und laufende Optimierung.",
  "products.category.chatbots": "Chatbots",
  "products.category.voiceAssistants": "Voice Assistants",
  "products.category.automation": "Automation",
  "products.category.analytics": "Analytics",
  "products.category.customSolutions": "Custom AI",
  "products.category.consulting": "Consulting",
  "products.keyFeatures": "Kernfunktionen",
  "products.viewDetails": "Details ansehen",
}

const translations: Partial<Record<Language, Record<string, string>>> = {
  de: defaultTranslations,
  "de-CH": {
    ...defaultTranslations,
    "nav.platforms": "Plattformen",
    "nav.solutions": "Loesige",
    "nav.pricing": "Priise",
    "nav.contact": "Kontakt",
  },
  en: {
    ...defaultTranslations,
    "nav.platforms": "Platforms",
    "nav.products": "Products",
    "nav.solutions": "Solutions",
    "nav.news": "AI Feed",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    "nav.language": "Language",
    "contact.title": "Contact",
    "products.title": "Products",
    "hero.titleSuffix": "under one strong AI brand.",
    "hero.subtitle":
      "LetAIwork4u connects premium software, AI automation, and new platform ideas. AnwaltSoft and beA4Outlook are being built as flagship products for law firms.",
    "hero.cta.platforms": "View platforms",
    "hero.cta.anwaltsoft": "Discover AnwaltSoft",
    "spline.cardText":
      "LETAIWORK4U brings your business to life with intelligent AI solutions. Create immersive experiences that transform your workflow and enhance productivity.",
    "home.ecosystem.eyebrow": "LetAIwork4u ecosystem",
    "home.ecosystem.title": "One umbrella brand for AI, LegalTech, voicebots, robotics, and new platform ideas.",
    "home.ecosystem.desc":
      "AnwaltSoft and beA4Outlook are being built as flagship products. Additional platforms can grow cleanly without reinventing the brand every time.",
    "home.ecosystem.cta": "View all platforms",
    "animated.prefix": "Your",
    "animated.suffix": "deserves better tools",
    "animated.word.business": "business",
    "animated.word.team": "team",
    "animated.word.workflow": "workflow",
    "animated.word.productivity": "productivity",
    "animated.word.strategy": "AI strategy",
    "animated.word.transformation": "digital transformation",
    "animated.word.automation": "automation",
    "animated.word.analytics": "analytics",
    "features.developers.title": "Built for developers",
    "features.developers.desc": "Designed for engineers, developers, and innovators who want to leverage AI in their projects.",
    "features.ease.title": "Ease of use",
    "features.ease.desc": "Our AI solutions are intuitive and accessible, requiring minimal technical expertise.",
    "features.pricing.title": "Transparent pricing",
    "features.pricing.desc": "Clear, predictable pricing with no hidden fees. Pay only for what you use.",
    "features.uptime.title": "99.9% Uptime guarantee",
    "features.uptime.desc": "Our robust infrastructure ensures your AI services are always available when you need them.",
    "features.multi.title": "Multi-tenant Architecture",
    "features.multi.desc": "Securely share AI resources across your organization with role-based access control.",
    "features.support.title": "24/7 AI Support",
    "features.support.desc": "Get help anytime with our AI-powered support system and dedicated human experts.",
    "features.improvement.title": "Continuous improvement",
    "features.improvement.desc": "Our AI models are constantly learning and improving to deliver better results over time.",
    "features.custom.title": "Custom solutions",
    "features.custom.desc": "We tailor our AI solutions to meet your specific business needs and challenges.",
    "capabilities.automation.title": "AI-Powered Automation",
    "capabilities.automation.desc": "Streamline your workflows with intelligent automation that learns and adapts to your business needs.",
    "capabilities.analytics.title": "Advanced Analytics",
    "capabilities.analytics.desc": "Gain actionable insights from your data with our powerful AI analytics tools.",
    "capabilities.security.title": "Secure AI Integration",
    "capabilities.security.desc": "Enterprise-grade security for all your AI implementations and data processing.",
    "capabilities.custom.title": "Custom AI Solutions",
    "capabilities.custom.desc": "Tailored AI solutions designed specifically for your industry and business challenges.",
    "capabilities.search.title": "Intelligent Search",
    "capabilities.search.desc": "Find exactly what you need with our AI-powered search technology that understands context and intent.",
    "footer.desc": "Umbrella brand for AI integration, voicebots, LegalTech, software, web design, and new AI projects.",
  },
  es: {
    ...defaultTranslations,
    "nav.products": "Productos",
    "nav.solutions": "Soluciones",
    "nav.pricing": "Precios",
    "nav.contact": "Contacto",
    "nav.language": "Idioma",
    "hero.titleSuffix": "bajo una marca de IA fuerte.",
    "hero.cta.platforms": "Ver plataformas",
    "hero.cta.anwaltsoft": "Descubrir AnwaltSoft",
    "spline.title": "Experiencia interactiva LETAIWORK4U",
    "spline.subtitle": "Explora nuestra plataforma de IA con visualizaciones 3D inmersivas",
    "spline.cardTitle": "Soluciones impulsadas por IA",
    "home.ecosystem.eyebrow": "Ecosistema LetAIwork4u",
    "home.ecosystem.title": "Una marca paraguas para IA, LegalTech, voicebots, robotica y nuevas plataformas.",
    "home.ecosystem.cta": "Ver todas las plataformas",
    "home.discover.title": "Descubre nuestras soluciones impulsadas por IA",
    "animated.prefix": "Tu",
    "animated.suffix": "merece mejores herramientas",
    "features.title": "Soluciones de IA que nos distinguen",
    "capabilities.title": "Capacidades impulsadas por IA",
    "testimonials.title": "Lo que dicen nuestros clientes",
    "footer.ecosystem": "Ecosistema",
  },
  it: {
    ...defaultTranslations,
    "nav.products": "Prodotti",
    "nav.solutions": "Soluzioni",
    "nav.pricing": "Prezzi",
    "nav.contact": "Contatto",
    "nav.language": "Lingua",
    "hero.titleSuffix": "sotto un forte marchio AI.",
    "hero.cta.platforms": "Vedi piattaforme",
    "hero.cta.anwaltsoft": "Scopri AnwaltSoft",
    "spline.title": "Esperienza interattiva LETAIWORK4U",
    "spline.subtitle": "Esplora la nostra piattaforma AI con visualizzazioni 3D immersive",
    "spline.cardTitle": "Soluzioni basate sull'AI",
    "home.ecosystem.eyebrow": "Ecosistema LetAIwork4u",
    "home.ecosystem.title": "Un marchio ombrello per AI, LegalTech, voicebot, robotica e nuove piattaforme.",
    "home.ecosystem.cta": "Vedi tutte le piattaforme",
    "home.discover.title": "Scopri le nostre soluzioni basate sull'AI",
    "animated.prefix": "La tua",
    "animated.suffix": "merita strumenti migliori",
    "features.title": "Soluzioni AI che ci distinguono",
    "capabilities.title": "Capacita basate sull'AI",
    "testimonials.title": "Cosa dicono i nostri clienti",
    "footer.ecosystem": "Ecosistema",
  },
  ar: {
    ...defaultTranslations,
    "nav.platforms": "المنصات",
    "nav.products": "المنتجات",
    "nav.solutions": "الحلول",
    "nav.news": "أخبار الذكاء الاصطناعي",
    "nav.pricing": "الأسعار",
    "nav.contact": "اتصال",
    "nav.language": "اللغة",
    "hero.titleSuffix": "تحت علامة قوية للذكاء الاصطناعي.",
    "hero.cta.platforms": "عرض المنصات",
    "hero.cta.anwaltsoft": "اكتشف AnwaltSoft",
    "spline.title": "تجربة LETAIWORK4U التفاعلية",
    "spline.subtitle": "استكشف منصتنا المدعومة بالذكاء الاصطناعي مع عروض ثلاثية الأبعاد",
    "spline.cardTitle": "حلول مدعومة بالذكاء الاصطناعي",
    "home.ecosystem.eyebrow": "منظومة LetAIwork4u",
    "home.ecosystem.title": "علامة واحدة للذكاء الاصطناعي وLegalTech وvoicebots والروبوتات والمنصات الجديدة.",
    "home.ecosystem.cta": "عرض كل المنصات",
    "home.discover.title": "اكتشف حلولنا المدعومة بالذكاء الاصطناعي",
    "animated.prefix": "عملك",
    "animated.suffix": "يستحق أدوات أفضل",
    "features.title": "حلول ذكاء اصطناعي تميزنا",
    "capabilities.title": "قدرات مدعومة بالذكاء الاصطناعي",
    "testimonials.title": "ماذا يقول عملاؤنا",
    "footer.ecosystem": "المنظومة",
  },
  zh: {
    ...defaultTranslations,
    "nav.platforms": "平台",
    "nav.products": "产品",
    "nav.solutions": "解决方案",
    "nav.news": "AI 动态",
    "nav.pricing": "价格",
    "nav.contact": "联系",
    "nav.language": "语言",
    "hero.titleSuffix": "汇聚在一个强大的 AI 品牌下。",
    "hero.cta.platforms": "查看平台",
    "hero.cta.anwaltsoft": "了解 AnwaltSoft",
    "spline.title": "LETAIWORK4U 互动体验",
    "spline.subtitle": "通过沉浸式 3D 可视化探索我们的 AI 平台",
    "spline.cardTitle": "AI 驱动的解决方案",
    "home.ecosystem.eyebrow": "LetAIwork4u 生态系统",
    "home.ecosystem.title": "一个覆盖 AI、LegalTech、语音机器人、机器人技术和新平台的品牌。",
    "home.ecosystem.cta": "查看所有平台",
    "home.discover.title": "探索我们的 AI 解决方案",
    "animated.prefix": "您的",
    "animated.suffix": "值得更好的工具",
    "features.title": "让我们与众不同的 AI 解决方案",
    "capabilities.title": "AI 驱动能力",
    "testimonials.title": "客户评价",
    "footer.ecosystem": "生态系统",
  },
  ja: {
    ...defaultTranslations,
    "nav.platforms": "プラットフォーム",
    "nav.products": "製品",
    "nav.solutions": "ソリューション",
    "nav.news": "AIフィード",
    "nav.pricing": "料金",
    "nav.contact": "お問い合わせ",
    "nav.language": "言語",
    "hero.titleSuffix": "強いAIブランドのもとに。",
    "hero.cta.platforms": "プラットフォームを見る",
    "hero.cta.anwaltsoft": "AnwaltSoftを見る",
    "spline.title": "LETAIWORK4U インタラクティブ体験",
    "spline.subtitle": "没入型3DビジュアルでAIプラットフォームを探索",
    "spline.cardTitle": "AI搭載ソリューション",
    "home.ecosystem.eyebrow": "LetAIwork4u エコシステム",
    "home.ecosystem.title": "AI、LegalTech、音声ボット、ロボティクス、新しいプラットフォームを束ねるブランド。",
    "home.ecosystem.cta": "すべてのプラットフォームを見る",
    "home.discover.title": "AIソリューションを見る",
    "animated.prefix": "あなたの",
    "animated.suffix": "にはより良いツールが必要です",
    "features.title": "私たちを際立たせるAIソリューション",
    "capabilities.title": "AI搭載機能",
    "testimonials.title": "お客様の声",
    "footer.ecosystem": "エコシステム",
  },
  th: {
    ...defaultTranslations,
    "nav.platforms": "แพลตฟอร์ม",
    "nav.products": "ผลิตภัณฑ์",
    "nav.solutions": "โซลูชัน",
    "nav.news": "ฟีด AI",
    "nav.pricing": "ราคา",
    "nav.contact": "ติดต่อ",
    "nav.language": "ภาษา",
    "hero.titleSuffix": "ภายใต้แบรนด์ AI ที่แข็งแกร่ง.",
    "hero.cta.platforms": "ดูแพลตฟอร์ม",
    "hero.cta.anwaltsoft": "รู้จัก AnwaltSoft",
    "spline.title": "ประสบการณ์โต้ตอบ LETAIWORK4U",
    "spline.subtitle": "สำรวจแพลตฟอร์ม AI ของเราด้วยภาพ 3D แบบ immersive",
    "spline.cardTitle": "โซลูชันขับเคลื่อนด้วย AI",
    "home.ecosystem.eyebrow": "ระบบนิเวศ LetAIwork4u",
    "home.ecosystem.title": "แบรนด์หลักสำหรับ AI, LegalTech, voicebots, หุ่นยนต์ และแพลตฟอร์มใหม่.",
    "home.ecosystem.cta": "ดูแพลตฟอร์มทั้งหมด",
    "home.discover.title": "ค้นพบโซลูชัน AI ของเรา",
    "animated.prefix": "",
    "animated.suffix": "ของคุณสมควรได้เครื่องมือที่ดีกว่า",
    "features.title": "โซลูชัน AI ที่ทำให้เราแตกต่าง",
    "capabilities.title": "ความสามารถที่ขับเคลื่อนด้วย AI",
    "testimonials.title": "ลูกค้าของเราพูดว่าอย่างไร",
    "footer.ecosystem": "ระบบนิเวศ",
  },
  fi: {
    ...defaultTranslations,
    "nav.products": "Tuotteet",
    "nav.solutions": "Ratkaisut",
    "nav.pricing": "Hinnat",
    "nav.contact": "Yhteys",
    "nav.language": "Kieli",
    "hero.titleSuffix": "vahvan AI-brändin alla.",
    "hero.cta.platforms": "Katso alustat",
    "hero.cta.anwaltsoft": "Tutustu AnwaltSoftiin",
    "spline.title": "LETAIWORK4U interaktiivinen kokemus",
    "spline.subtitle": "Tutustu AI-alustaamme immersiivisten 3D-visualisointien avulla",
    "spline.cardTitle": "AI-pohjaiset ratkaisut",
    "home.ecosystem.eyebrow": "LetAIwork4u-ekosysteemi",
    "home.ecosystem.title": "Yksi kattobrändi AI:lle, LegalTechille, voiceboteille, robotiikalle ja uusille alustoille.",
    "home.ecosystem.cta": "Katso kaikki alustat",
    "home.discover.title": "Tutustu AI-ratkaisuihimme",
    "animated.prefix": "Sinun",
    "animated.suffix": "ansaitsee paremmat työkalut",
    "features.title": "AI-ratkaisut, jotka erottavat meidät",
    "capabilities.title": "AI-pohjaiset kyvykkyydet",
    "testimonials.title": "Mitä asiakkaamme sanovat",
    "footer.ecosystem": "Ekosysteemi",
  },
  nl: {
    ...defaultTranslations,
    "nav.products": "Producten",
    "nav.solutions": "Oplossingen",
    "nav.pricing": "Prijzen",
    "nav.contact": "Contact",
    "nav.language": "Taal",
    "hero.titleSuffix": "onder een sterk AI-merk.",
    "hero.cta.platforms": "Bekijk platforms",
    "hero.cta.anwaltsoft": "Ontdek AnwaltSoft",
    "spline.title": "LETAIWORK4U interactieve ervaring",
    "spline.subtitle": "Ontdek ons AI-platform met immersieve 3D-visualisaties",
    "spline.cardTitle": "AI-gedreven oplossingen",
    "home.ecosystem.eyebrow": "LetAIwork4u ecosysteem",
    "home.ecosystem.title": "Een overkoepelend merk voor AI, LegalTech, voicebots, robotica en nieuwe platformideeen.",
    "home.ecosystem.cta": "Bekijk alle platforms",
    "home.discover.title": "Ontdek onze AI-oplossingen",
    "animated.prefix": "Uw",
    "animated.suffix": "verdient betere tools",
    "features.title": "AI-oplossingen die ons onderscheiden",
    "capabilities.title": "AI-gedreven mogelijkheden",
    "testimonials.title": "Wat onze klanten zeggen",
    "footer.ecosystem": "Ecosysteem",
  },
  fr: {
    ...defaultTranslations,
    "nav.products": "Produits",
    "nav.solutions": "Solutions",
    "nav.pricing": "Tarifs",
    "nav.contact": "Contact",
    "nav.language": "Langue",
    "hero.titleSuffix": "sous une marque IA forte.",
    "hero.cta.platforms": "Voir les plateformes",
    "hero.cta.anwaltsoft": "Decouvrir AnwaltSoft",
    "spline.title": "Experience interactive LETAIWORK4U",
    "spline.subtitle": "Explorez notre plateforme IA avec des visualisations 3D immersives",
    "spline.cardTitle": "Solutions propulsees par l'IA",
    "home.ecosystem.eyebrow": "Ecosysteme LetAIwork4u",
    "home.ecosystem.title": "Une marque ombrelle pour l'IA, LegalTech, les voicebots, la robotique et les nouvelles plateformes.",
    "home.ecosystem.cta": "Voir toutes les plateformes",
    "home.discover.title": "Decouvrez nos solutions IA",
    "animated.prefix": "Votre",
    "animated.suffix": "merite de meilleurs outils",
    "features.title": "Des solutions IA qui nous distinguent",
    "capabilities.title": "Capacites propulsees par l'IA",
    "testimonials.title": "Ce que disent nos clients",
    "footer.ecosystem": "Ecosysteme",
  },
  sv: {
    ...defaultTranslations,
    "nav.products": "Produkter",
    "nav.solutions": "Loesningar",
    "nav.pricing": "Priser",
    "nav.contact": "Kontakt",
    "nav.language": "Sprak",
    "hero.titleSuffix": "under ett starkt AI-varumarke.",
    "hero.cta.platforms": "Visa plattformar",
    "hero.cta.anwaltsoft": "Upptack AnwaltSoft",
    "spline.title": "LETAIWORK4U interaktiv upplevelse",
    "spline.subtitle": "Utforska var AI-plattform med immersiva 3D-visualiseringar",
    "spline.cardTitle": "AI-drivna loesningar",
    "home.ecosystem.eyebrow": "LetAIwork4u ekosystem",
    "home.ecosystem.title": "Ett paraplyvarumarke for AI, LegalTech, voicebots, robotik och nya plattformar.",
    "home.ecosystem.cta": "Visa alla plattformar",
    "home.discover.title": "Upptack vara AI-loesningar",
    "animated.prefix": "Din",
    "animated.suffix": "fortjanar battre verktyg",
    "features.title": "AI-loesningar som skiljer oss fran mangden",
    "capabilities.title": "AI-drivna funktioner",
    "testimonials.title": "Vad vara kunder sager",
    "footer.ecosystem": "Ekosystem",
  },
  pt: {
    ...defaultTranslations,
    "nav.products": "Produtos",
    "nav.solutions": "Solucoes",
    "nav.pricing": "Precos",
    "nav.contact": "Contato",
    "nav.language": "Idioma",
    "hero.titleSuffix": "sob uma marca forte de IA.",
    "hero.cta.platforms": "Ver plataformas",
    "hero.cta.anwaltsoft": "Conhecer AnwaltSoft",
    "spline.title": "Experiencia interativa LETAIWORK4U",
    "spline.subtitle": "Explore nossa plataforma de IA com visualizacoes 3D imersivas",
    "spline.cardTitle": "Solucoes impulsionadas por IA",
    "home.ecosystem.eyebrow": "Ecossistema LetAIwork4u",
    "home.ecosystem.title": "Uma marca guarda-chuva para IA, LegalTech, voicebots, robotica e novas plataformas.",
    "home.ecosystem.cta": "Ver todas as plataformas",
    "home.discover.title": "Conheca nossas solucoes de IA",
    "animated.prefix": "Seu",
    "animated.suffix": "merece ferramentas melhores",
    "features.title": "Solucoes de IA que nos diferenciam",
    "capabilities.title": "Capacidades impulsionadas por IA",
    "testimonials.title": "O que nossos clientes dizem",
    "footer.ecosystem": "Ecossistema",
  },
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("de")
  const currentLanguage = languageOptions.find((option) => option.code === language) ?? languageOptions[1]
  const dictionary = translations[language] ?? defaultTranslations

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem("letaiwork4u-language") as Language | null
    if (savedLanguage && languageOptions.some((option) => option.code === savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    window.localStorage.setItem("letaiwork4u-language", language)
    document.documentElement.lang = language
    document.documentElement.dir = currentLanguage.dir
  }, [currentLanguage.dir, language])

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      currentLanguage,
      isRTL: currentLanguage.dir === "rtl",
      t: (key: string) => dictionary[key] ?? defaultTranslations[key] ?? key,
    }),
    [currentLanguage, dictionary, language],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
